### ISSUE TITLE
Sovrn performance in Prebid 0.10

### ISSUE THREAD

**Issue by CarsonBanov** [prebid/Prebid.js#439] opened 2016-07-07 21:35 UTC
We are seeing very high discrepancy for Sovrn after moving to Prebid 0.10.  We rolled back to 0.9 and the discrepancy went away.  

Debugging (for me) shows:
* the requests to Sovrn go out and bids return
* `bidfactory.createBid` a `bid` is successfully created for each response that has `bid.ad` which is a combo of `responseAd` and `responseNurl` and has `bid.adId` which is a unique identifier.
* `bidmanager.addBidResponse` a bid response is then added using the aforementioned `bid` and the correct `placementCode`
* if the bid wins, `pbjs.renderAd` is successfully called with the right `bid.adId` and attempts to render the ad.
* This appears to mean everything is going well; however, locally, sometimes the creative does not render (this may be a red herring since I have just seen it testing locally).

I know there are a lot of steps in the process, and all of them appear to be working to some extent, so it may not be easy to debug.  So I guess my main question is:

*Has this happened to anyone else?* 

.cc @cliffliang @pdramos1 @nanek @ehoch

**Comment by pdramos1** [comment] 2016-07-07 22:58
We haven't seen this currently . But that doesn't mean that it isn't real.  We will however be looking into this. One thing to note is that we are currently in the process of setting up a single point of corporate contact for issues like this. You should see that contact change next week.

**Comment by toddynho** [comment] 2016-07-08 00:23
We were investigating a discrepancy today as well, however, we're still on 0.9.1 and not 0.10 yet. The discrepancy is about 32%. I don't have much more than that right now though, still trying to debug on our side to make sure it's not us.

**Comment by ehoch** [comment] 2016-07-08 11:51
No additional discrepancies on 0.10.0 for us, just overall lower requests and Sovrn performance since the upgrade.

**Comment by mkendall07** [comment] 2016-07-08 12:30
@CarsonBanov 
What's the nature of the discrepancy? Do your pages do a lot of refreshes?

**Comment by CarsonBanov** [comment] 2016-07-08 15:41
No refreshes, just load ads one time.  We are seeing over 10% impression discrepancy on some ad units which results in a similar revenue discrep.  I'll try to get more info from our data guy, he was the one who flagged this originally.

**Comment by pdramos1** [comment] 2016-07-08 16:07
Hey guys, I want to also mention that while our technical group is starting to look into this issue . You are always welcome to ring up your account contacts here at sovrn and let them know as well so the appropriate tickets are created and tracked on our end.

**Comment by mkendall07** [comment] 2016-07-21 01:23
any update on this from anyone? If it's something related to the bidder and not the prebid project I'd like to close.

**Comment by sovrnoss** [comment] 2016-07-22 20:58
After investigating we have not found any problems with the sovrn bidder on 0.10.0. The issues mentioned have been isolated to specific setups. We would agree that #439 can be closed. As @pdramos1 mentioned, any concerns with sovrn performance can be sent to your sovrn representative, or can be sent to sovrnoss@sovrn.com. 

Thanks, sovrn Support Team.

**Comment by mkendall07** [comment] 2016-07-22 20:59
thx

**Comment by ehoch** [comment] 2016-07-26 11:48
@sovrnoss Our issue has still not been resolved. I'm going to send you an email, but I believe the issue is occurring only for pubs sending multiple requests to the same placements / ad units. Have you guys tested those setups?

**Comment by sovrnoss** [comment] 2016-07-26 17:33
@ehoch 

Yes, we have tested this case in v0.10. Please do send an email, and we will take a look at your setup. The sovrn tagid can only support one size, so the method for sending multiple requests for the same ad unit would be to include multiple sovrn bidder objects.

Again, please shoot an email to sovrnoss@sovrn.com and our support team can review the issue and try to resolve.

Thanks, sovrn Support Team.

**Comment by nanek** [comment] 2016-07-26 23:50
I believe the commit below is causing the issue for us. This commit is post v0.10, but was mistakenly included in our v0.10 build during testing. I have not tested v0.11, but would expect this issue to exist there as well.

https://github.com/prebid/Prebid.js/commit/6e9068ec8d8c06e2e3b3d862709f7b2ffe39290a#diff-96cd0debf7b766d72d2bcf987385e960

If multiple sovrn bidder objects are used for the same ad unit, the bid.adId for all bids are set to the same id, the bidRequest.bidId of first bid response. Then when the adId is looked up in renderAd, it picks the first one, as multiple bid responses all have the same adId.

Can we re-open this ticket or start a new one?

**Comment by sovrnoss** [comment] 2016-07-27 04:03
@nanek 

Yes. We have also confirmed this bug. Thank you for pointing out this issue. Like you mention, this probably should be opened in a prebid v0.11 ticket since the commit is post v0.10.

What happens is exactly how you described.

We've created a ticket for our sovrn engineers to investigate.
We will need the bidmanager to be modified to accommodate multiple sovrn bidders per ad unit. This is the only way that sovrn can currently handle multi-sized ad units.

Thanks, sovrn Support Team.

**Comment by ehoch** [comment] 2016-07-27 12:39
@mkendall07 Can we get this re-opened?

**Comment by chaqu170** [comment] 2016-07-29 17:34
If we have a single-page app that calls refresh on the same ad units, is there a good chance that this issue would also be present there?

**Comment by protonate** [comment] 2016-07-29 18:08
@chaqu170 I believe the issue is caused by having a placement that supports multiple sizes, in which case the Sovrn configuration will have an `adUnits` entry per size supported for that placement. SPA and using refresh to request more bids in itself should not cause the issue to be present.

**Comment by protonate** [comment] 2016-08-09 18:18
This has been addressed with #498, closing.

**Closed by protonate** 2016-08-09 18:18 UTC
Labels: needs review
