### ISSUE TITLE
UserId module references `usersync` and not `userSync`

### ISSUE THREAD

**Issue by ETNOL** [prebid/Prebid.js#3818] opened 2019-05-10 15:44 UTC
@idettman Should this be using `userSync` and not `usersync`?

_Originally posted by @ETNOL in https://github.com/prebid/Prebid.js/pull/3424#issuecomment-482617963_

**Comment by bretg** [comment] 2019-05-14 17:28
Wow - that's an unfortunate one. Hard to believe no one caught that in several reviews. Ultimately it's my fault because that's how the original issue specified it. https://github.com/prebid/Prebid.js/issues/3046

At least the documentation is aligned with the code. 

@idettman - please modify the code to look for both `usersync` and `userSync`, explaining in a comment that a future major release will deprecate the lowercase version.

**Comment by bretg** [comment] 2019-05-20 19:15
Confirmed that this is part of PR 3831. Closing this issue.

**Closed by bretg** 2019-05-20 19:15 UTC
