### ISSUE TITLE
Failing test and render issue on Internet Explorer

### ISSUE THREAD

**Issue by matthewlane** [prebid/Prebid.js#403] opened 2016-06-09 23:36 UTC
Running Prebid.js automated tests using Internet Explorer 9 on Windows 7 with the command `gulp serve --browsers=IE` produces one failing test:

```
Failed Tests:
Utils
   createInvisibleIframe
      return iframe - border
         IE 9.0.0 (Windows 7 0.0.0)
            1) '0' deepEqual '0px'

```

Additionally, the ad from the [basic example](http://prebid.org/dev-docs/examples/basic-example.html) only partially renders:

![basic-example-render](https://cloud.githubusercontent.com/assets/924348/15949939/d1cdf662-2e5f-11e6-914f-5679ac468f0f.PNG)

It should also be noted that IE9 displays the header section of the Prebid homepage with a purple background, whereas every other browser I've checked displays a blue background:

![prebid-homepage](https://cloud.githubusercontent.com/assets/924348/15950016/1d216e32-2e60-11e6-8952-16cde22607e7.PNG)

**Comment by mkendall07** [comment] 2016-06-15 15:43
@matthewlane 
Thanks. For the failed test in IE, that's a browser specific implementation detail that we probably don't need to worry about. We can most likely remove that check. 

For the display issue, we should dig into it and see what the root cause is.

**Comment by mkendall07** [comment] 2016-07-08 12:38
@matthewlane 
Can you remove the IE failed test and close this out? Thanks

**Closed** 2016-07-09 14:33 UTC
Labels: needs update
