### ISSUE TITLE
Support for 1 request for all bids in Appnexus adapter

### ISSUE THREAD

**Issue by ialex** [prebid/Prebid.js#350] opened 2016-05-12 14:52 UTC
As a publisher i use multiple networks using the appnexus adapter as a base for Header bidding, but the adapter makes 1 request per bid configured and that decreases the performance for all networks since each requests takes arround 200ms. usually the first networks configured are the ones that get most winnings.

Maybe this time could be reduced if the adapter and API supported sending just 1 request for all bids for each network.

**Comment by mkendall07** [comment] 2016-05-12 16:04
@ialex 
Yes we are working on switching out to the `appnexusAst` adapter which uses a single request mode. Currently this can be used by doing a custom build of prebid.js. We don't yet have support for aliasing the adapter.

**Comment by protonate** [comment] 2016-06-07 21:01
Related: #322

**Comment by mkendall07** [comment] 2016-07-21 01:29
closing this as a duplicate of #322 (it will cover both scenarios).

**Closed by mkendall07** 2016-07-21 01:29 UTC
Labels: feature
