### ISSUE TITLE
mediaType.Banner is added when only requesting video

### ISSUE THREAD

**Issue by ReinoutStevens** [prebid/Prebid.js#3256] opened 2018-11-02 16:23 UTC
## Type of issue
Bug

## Description
When requesting only a videoAd somewhere mediaTypes.banner.size is added by prebid.
The rubicon adapter warns that a multisize ad is requested (and not yet supported).
This is not visible when asking pbjs.adUnits, where the correct mediaType is present, but tracing auction the banner mediatype is added somewhere

## Steps to reproduce
Request a videoAd:

```
    var videoAdUnit = {
      code: 'video',
      mediaTypes: {
        video: {
          context: 'instream',
          playerSize: [[640, 480]],
        },
      },
      bids: [
        {
          bidder: 'rubicon',
          params: {
            zoneId: 755208,
            accountId: '16980',
            siteId: '152672',
            video: {
              playerWidth: '640',
              playerHeight: '480',
              size_id: 201,
              language: 'en',
            }
          }
        }
      ]
    };
```

## Test page
http://jsfiddle.net/9yz46dof/
### Expected results
Rubicon adapter shouldnt complain

### Actual results
Rubicon complains

## Platform details
latest prebid

**Comment by snapwich** [comment] 2018-11-08 21:14
closed as duplicate of #3269

**Closed by snapwich** 2018-11-08 21:14 UTC
