### ISSUE TITLE
seeing floors stopping auction id change, with video module

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#9710] opened 2023-03-24 17:28 UTC
## Type of issue
potential bug, not sure

## Description
I'm trying to do a simple test with floors and the video module but i'm seeing that when i add floors, the auction id stops changing. I'm not 100% sure if this is a prob or if i've ballzed up something, i'm basically just trying to set a simple one price floor for video and using this, should this work?

## Steps to reproduce
if floors setting addd, for basic floor, auction Id replicates, take it out auction ID changes in each bid
floors: {
                    auctionDelay: 100,
                    enforcement: {
                      enforceJS: false,
                      floorDeals: true,
                    },
                    floorMin: 0.05,
                      data: {
                        currency: 'GBP',
                        skipRate: 5,
                        modelVersion: 'Sports Ad Unit Floors',
                        schema: {
                            fields: ['mediaType']
                        },
                        values: {
                            'video': 0.50
                        }
                      }
                    },

## Test page
@ChrisHuie has the test page

### Expected results
auction ID changing

### Actual results

auction ID replicates on bids

## Platform details
v7.41.0, mac, chrome

## Other information

![seeing_floors_stopping_auction_id_change__with_video_module_·_Issue__9702_·_prebid_Prebid_js_🔊](https://user-images.githubusercontent.com/8503167/227597481-0956fb20-31c6-47d9-a160-5ca66ea08915.png)

pubmatic shows the floors info:
![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_NewVideoModuleNeuwoGolf_html](https://user-images.githubusercontent.com/8503167/227597947-fa080fa4-2b66-457a-9922-b726b2149bd2.png)

no prebid errors thrown

**Comment by patmmccann** [comment] 2023-03-27 16:02
@spormeon are you able to confirm the issue without using Professor Prebid? Is it possible PP is reporting the wrong value and js is working fine?

**Comment by spormeon** [comment] 2023-03-27 16:08
ye here you go:  
![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_NewVideoModuleNeuwoGolf_html](https://user-images.githubusercontent.com/8503167/227999457-0726b97a-c84a-47ab-9797-1cb35aead487.png)

**Comment by spormeon** [comment] 2023-04-18 21:53
Update on this, I've set this to a complete bare bones min floors setup but the auction ID continues to repeat as before,  I dont see whats making any differnce at all here:

var floorPrices = {
          currency: 'GBP',
          floor: 0.50
          // skipRate: 0.2, // Set skip rate for video media type 0-1 0 no skipping, 1 all ads skipped
          // modelVersion: '1.0' // Set floor price model version for video media type
      };


setConfig:
floors: {
            auctionDelay: 200,
            //   enforcement: {
            //   enforceJS: false,
            //   floorDeals: true,
            // },
            enabled: true,
            // Set global floor prices for all ad units
            global: floorPrices,
            // Set ad unit specific floor prices
            // mediaType: {
            //   video: floorPrices // Set floor prices specifically for video media type
            // }
          },

**Comment by spormeon** [comment] 2023-04-19 08:18
also tried setting floors at adUnit level with the blank floors array in setConfig, same behaviour, auction ID repeats

**Comment by karimMourra** [comment] 2023-05-24 14:42
Based on my debugging, this appears to be unrelated to the video module.
I was able to reproduce this bug without even using the video module. Also, if I use the video module without the `priceFloors` module, the bug does not reproduce. I suggest closing and opening a bug for the `priceFloors` module. 

The integration example called [bidRequestScheduling](https://github.com/prebid/Prebid.js/blob/master/integrationExamples/videoModule/videojs/bidRequestScheduling.html) makes a bidRequest after every 10 seconds of content. The following screenshot shows that the auction IDs are different
<img width="916" alt="Screen Shot 2023-05-24 at 10 13 47 AM" src="https://github.com/prebid/Prebid.js/assets/12138319/7a57d407-8b10-49b8-a8ac-b8d6c4956993">

**Comment by dgirardi** [comment] 2023-07-12 14:51
The problem is an invalid argument passed to requestBids, that - because it's always the same object - ends up forcing the auction ID from the second invocation onwards:

![Image](https://github.com/prebid/Prebid.js/assets/10151381/045c17e0-3fef-4dbd-b6a5-51472e92cf97)

If you use `addAdUnits`, there's no need to pass adUnits to requestBids again; and if you do pass them, it should have the form `requestBids({adUnits})` - [reference](https://docs.prebid.org/dev-docs/publisher-api-reference/requestBids.html).

**Comment by patmmccann** [comment] 2023-07-12 14:54
@spormeon we wasted a lot of overhead to identify a simple fix because of your caginess around test pages. We don't plan to support that again.

**Closed** 2023-07-12 14:54 UTC
Labels: bug

**Comment by spormeon** [comment] 2023-07-12 15:02
its from the video module files:  
![bidRequestScheduling_html_—_Prebid_js](https://github.com/prebid/Prebid.js/assets/8503167/1a4cf6b0-3296-463b-94bf-5f86d813234d)
