### ISSUE TITLE
smartadserver bug/ problem with Video

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#6611] opened 2021-04-16 17:49 UTC
@lowendavid @tadam75 ( i think you are the smart guys)  hopefully someone from smartadserver can pick this up.

I think you have a problem with your "video object" which messes up things if people have stuff defined on the mediaTypes,  you have protocol and can only define 1, should be protocols and an array? 

startDelay, is startdelay and there is No 1

![DevTools_-_cheftalk_com_ads_final_-2](https://user-images.githubusercontent.com/8503167/115064169-853c8480-9ee4-11eb-9183-e48c57e20cbf.png)

**Comment by patmmccann** [comment] 2021-04-16 17:58
Related to #6512

**Comment by spormeon** [comment] 2021-04-16 18:06
I'm presuming its also why it throws an error for s2s but i ain't sure if related/ something different but guessing, one fixes the other maybe:

![DevTools_-_cheftalk_com_ads_final_-3](https://user-images.githubusercontent.com/8503167/115065964-c3d33e80-9ee6-11eb-8c1c-90568bc57cb7.png)

**Comment by mlapeyre3** [comment] 2021-04-22 08:52
Hello @spormeon, thanks for the headsup!
Until Prebid 4.0, our video parameters are indeed protocol and startDelay. From our bidder perspective:
* protocol is the **Maximum** open RTB video protocol supported (e.g: 8  for VAST 4.0 Wrapper)
* startDelay was defined camelCase (1 (generic pre-roll, default), 2 (generic mid-roll), 3 (generic post-roll), at the time of the development, which does not match the values from OpenRTB)

Since prebid 4.0 we haven't worked on the video part of our bidder adapter, that's why there was no modifications on how the video parameters are sourced. In https://prebid.org/blog/prebid-js-release-4-0/ there was a mention about "Adapter reviewers will now enforce that video parameters be retrieved from the mediaTypes.video object." but as we haven't work on video since then ...

Besides the blogpost, is there a documentation where we can find the exhaustive list of video parameters that can be sourced directly from the mediatype?

The current setup of our bidder is still in a unique/free form taxonomy, but if the parameters are defined in **our** video object, there should be no error.

Looking forward the relevant specs, so that we can work on it in a future iteration :)

Thanks!

**Comment by spormeon** [comment] 2021-04-22 09:06
@mlapeyre3 are you on the slack channels, whats your handle?  I can give you a test page, juts don't like putting it in public

**Comment by spormeon** [comment] 2021-04-22 09:34
ah right i now see, you actually have a param called "video", how confusing is that:
params: {
        networkId: vvvv,
        //domain: 'https://prg.smartadserver.com',
        siteId: 4yyy,
        pageId: 13yyyy,
        formatId: 9yyyyy,
        //bidfloor: 0.01
    video: {
        startDelay: 1,
        protocol: 6
    }
}


and not like this, which "everyone" else uses:
params: {
        networkId: vvvv,
        //domain: 'https://prg.smartadserver.com',
        siteId: 4yyy,
        pageId: 13yyyy,
        formatId: 9yyyyy,
        //bidfloor: 0.01
},
    video: {
        startDelay: 1,
        protocol: 6
    }

**Comment by spormeon** [comment] 2021-04-22 09:54
@mlapeyre3 what throws the error 400 for you when on S2S as that still don't work.  Is that S2S not "turned on" in effect in your system?

**Comment by spormeon** [comment] 2021-04-29 14:40
@mlapeyre3 any info here.?  The client side seems to work ok, getting a good selection of bids etc but switching it over to s2s and we get zip, nada, nothing

**Comment by spormeon** [comment] 2021-06-01 16:35
@patmmccann mlapeyre3 is their " CEO" I think, for your question on slack, not replied on here since 29th April ( to me at least), maybe they have all disapeared? lol

**Comment by patmmccann** [comment] 2021-06-01 17:22
@mlapeyre3 the list is at https://github.com/prebid/Prebid.js/issues/5237

**Comment by mlapeyre3** [comment] 2021-06-01 20:42
Hello guys, sorry I don’t know why I haven’t been receiving the notifications anymore. The issue escaped my mind. I will ask the team to look at it and push an update by next week.
Thanks !

**Comment by patmmccann** [comment] 2021-06-02 01:38
Hi @mlapeyre3 ! 

The deadline to make prebid 5 is June 9; but we're looking to do all the merges on or before June 7. This issue is a duplicate of #6512 for your adapter.  All the adapters in that issue are not being ported to 5.

**Comment by ChrisHuie** [comment] 2021-06-21 09:41
closing with #6944 merge

**Closed by ChrisHuie** 2021-06-21 09:41 UTC
