### ISSUE TITLE
Build Errors for Sonobi, Nginad & Aardvark in version 0.10.0??

### ISSUE THREAD

**Issue by internetchris** [prebid/Prebid.js#450] opened 2016-07-15 16:43 UTC
Hey group,

When I checkout this version and run `gulp build` I see the following errors. Seems a little concerning. 

<img width="734" alt="screen shot on 2016-07-15 at 10-38-31" src="https://cloud.githubusercontent.com/assets/45402/16881754/e42cdb36-4a78-11e6-90e6-0327d82e35b1.png">

**Comment by matthewlane** [comment] 2016-07-15 20:58
We definitely want to limit errors reported by linting tools. In some cases though, code causing these errors is valid and intentional even though the linter doesn't recognize it. This is the case with the sonobi.js `break` fall through for example, which was confirmed as intentional by the submitter. `gulp build` should still be producing a functional output file--if it's not, due to linting errors or for any other reason, please let us know.

**Comment by mkendall07** [comment] 2016-07-21 01:24
This is resolved in 0.11.0 release.

**Closed by mkendall07** 2016-07-21 01:24 UTC
Labels: Build process
