### ISSUE TITLE
userSync only fire once when using refreshes

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#4027] opened 2019-07-25 12:06 UTC
is there a way to make userSync only fire once on first load, as when using refreshes it fires the userSync again and this is now throwing as a warning in 2.25.0,  can there be a setting in the config or something?  There is no benefit in firing the userSync on every refresh, only needs to fire once on first load?

userSync: {
        iframeEnabled: true,
        syncsPerBidder: 10, // and no more than 3 syncs at a time
        syncDelay: PREBID_TIMEOUT*2.5, // 5 seconds after the auction
      filterSettings: { iframe: { bidders: ['xxxxxx'], filter: 'exclude' }, image:  { bidders: '*', filter: 'include' } },
      enableOverride: true, // publisher will call `pbjs.triggerUserSyncs()`

syncOnce: true  // SOMETHING LIKE THIS MAYBE?

       },

**Comment by bretg** [comment] 2019-07-28 18:12
Asking @msm0504 to take a look in our next sprint. 
Requested behavior is that there's a new flag on the `userSync` config object that defines whether only the first call to `requestBids()` executes userSync or whether all invocations do. Default would be `true`. 
Use a GLOBAL state variable that allows for multiple instances of PBJS running in the page.

**Comment by snapwich** [comment] 2019-07-29 17:10
Can you clarify on what warning you're seeing? i'm wondering if it is related to: #3984

If you're refreshing an adUnit then the syncs should not fire again unless you added bidders since the last auction. If the warning you're referring to is `utils.logWarn(`already registered syncs for "${bidder}"`);` that shouldn't be an issue as it doesn't mean the sync is actually firing but being prevented from firing.  In fact, maybe it should be a logMessage because it's more just FYI.

If you're seeing a different warning and syncs are indeed firing again without adding bidders, then that's probably a bug.

**Comment by spormeon** [comment] 2019-07-29 17:34
here is the warning:
prebid2.25.0adyjs.js:3 Prebid WARNING: already registered syncs for "somoaudience"
F @ prebid2.25.0adyjs.js:3
prebid2.25.0adyjs.js:3 Prebid WARNING: already registered syncs for "districtmDMX"
F @ prebid2.25.0adyjs.js:3
prebid2.25.0adyjs.js:3 Prebid WARNING: already registered syncs for "triplelift"
F @ prebid2.25.0adyjs.js:3
prebid2.25.0adyjs.js:3 Prebid WARNING: already registered syncs for "oftmedia"
F @ prebid2.25.0adyjs.js:3

**Comment by snapwich** [comment] 2019-07-29 17:47
Thanks, that's what I had assumed and that's expected behavior after the userSync update in #3984.  I'll update it to be a logMessage rather than a warning and update the verbiage of the message to clarify that the sync is not firing again.

**Comment by spormeon** [comment] 2019-07-29 17:50
ok sure, thanks

**Comment by snapwich** [comment] 2019-07-30 16:01
The updated messaging has been merged and will go out in the next release so I'm going to close this issue unless you have any other questions.

**Closed by snapwich** 2019-07-30 16:01 UTC
