### ISSUE TITLE
Bids are being set twice

### ISSUE THREAD

**Issue by jlai1001** [prebid/Prebid.js#334] opened 2016-04-27 19:40 UTC
In Google publisher console, page request tab shows bids coming from prebid are being set twice, first  with no value, second time with value. Not sure if it is a bug.
![google_console](https://cloud.githubusercontent.com/assets/11430320/14865476/d1252464-0c8c-11e6-8a70-6d9ce738d8bb.PNG)

**Comment by mkendall07** [comment] 2016-04-27 19:47
@jlai1001 
As of the implementation time, DFP didn't seem to have an API to clear targeting for an individual key. Since we don't want to send "stale" bids from previous request, prebid first sets each key to an empty string to "clear" it. Then it sets the actual targeting. So this is expected behavior.

**Comment by protonate** [comment] 2016-04-29 16:24
Closing this as expected behavior, comment to reopen with additional info.

**Closed by protonate** 2016-04-29 16:24 UTC
Labels: question
