### ISSUE TITLE
Discrepancies due to duplicates with v.0.23.0

### ISSUE THREAD

**Issue by gitsh84** [prebid/Prebid.js#1359] opened 2017-07-10 20:24 UTC
## Description
One of our demand partners has reported very high discrepancies in impressions (of course, less impressions than what's reported in DFP).
The claim is that there are a lot of duplicate impressions and therefore the impressions are regarded as "invalid" and discarded.
Any idea how something can that could happen ?

Also a related question - Can somebody explain what is the loop for in the DFP creative ? (as seen [here](http://prebid.org/adops/send-all-bids-adops.html)). I guess it's some kind of fails safe to make sure the ad is rendered but it seems like a potential culprit for such issues, no ?

Thanks.

**Comment by mkendall07** [comment] 2017-07-18 13:22
Discrepancies are usually caused by refreshes to ad units on the page. Make sure that all bids requested have ample time to be displayed before more refreshes are requested.

**Comment by gitsh84** [comment] 2017-07-20 11:40
Hey @mkendall07, thanks for your reply. I'm 99% certain this is not the case here. Our refresh interval are very big (in minutes) also I've played around with interval between refreshes and seen no changes in discrepancies.
Also I think that discrepancies caused by refreshes will likely be "missing impressions" on the demand side and no duplicates as they claim.

Do you happen to know/understand the piece of code with the loop in the DFP creative (as seen here) ?

Thanks again.

**Comment by mkendall07** [comment] 2017-07-20 12:11
@gitsh84 
Can you provide additional details on the issue? Which bidder, discrepancy rate, does it affect all pages/sizes etc. 

Regarding the creative, yes the loop is for when the ad is loaded inside a nested iframe and it looks for the `pbjs` global. The `pbjs` global is not always in the `top.window` so it iterates up the iframes instead.

**Comment by mkendall07** [comment] 2017-07-20 12:13
You can also use the `window.top` method for invoking the creative render if you know prebid is always loaded in the top window. Use https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/creative_rendering.html#L3
Instead for your creative code.

**Comment by mkendall07** [comment] 2017-08-15 16:33
Closing because no further information was provided.

**Closed by mkendall07** 2017-08-15 16:33 UTC
