### ISSUE TITLE
Prebid basic example not working

### ISSUE THREAD

**Issue by michelangelo246** [prebid/Prebid.js#8240] opened 2022-03-30 19:15 UTC
## Type of issue
bug

## Description
The Prebid.js basic example is no longer being rendered.

## Test page
Go to the following [fiddle](https://jsfiddle.net/Prebid_Examples/94jt62b8/), which can be found at the Prebid basic example [page](https://docs.prebid.org/dev-docs/examples/basic-example.html).

### Expected results
The Prebid placeholder ad would be rendered.

### Actual results
Only the "House Ad" is displayed

## Platform details
N. A.

## Other information
This started to happen a few days ago.

**Comment by dgirardi** [comment] 2022-03-30 19:49
I believe this is because the SSP (appnexus) is offering no bid; not sure what could have caused that to change recently.

```
{"version":"3.0.0","tags":[{"uuid":"3499c3194b6be5","tag_id":13144370,"auction_id":"2635635334196713667","nobid":true,"ad_profile_id":0},{"uuid":"2c1af50bd80e75","tag_id":13144370,"auction_id":"8655612242182448236","nobid":true,"ad_profile_id":0}]}
```

[jsfiddle.net.zip](https://github.com/prebid/Prebid.js/files/8383661/jsfiddle.net.zip)

**Comment by patmmccann** [comment] 2022-03-31 12:36
This is a dupe of #7365 

Prebid needs to replace the appnexus bidder.

**Closed by patmmccann** 2022-03-31 12:36 UTC
