### ISSUE TITLE
Request to support for Fledge and Topics (Privacy Sandbox)

### ISSUE THREAD

**Issue by JoelPM** [prebid/Prebid.js#8333] opened 2022-04-28 16:36 UTC
## Type of issue
Feature request

## Description
Fledge and Topics have entered origin trials and various DSPs are looking to begin testing, which requires SSPs to support these Privacy Sandbox initiatives. For SSPs to support testing, we need our supply sources to support Fledge/Topics, and for most of us that means Prebid.js and Open Bidding. There is a (very) high-level proposal on how this could work for Fledge [here](https://github.com/JoelPM/prebid-td/blob/main/PrebidFledge.md). We are somewhat blocked until we know what GAM will do (issue [here](https://github.com/google/ads-privacy/issues/57)) but I believe we can at least come up with a prototype for how we think it should work.

## Other information

Nice looking flowchart that needs a lot more detail:
![Prebid/Fledge sequence diagram](https://raw.githubusercontent.com/JoelPM/prebid-td/main/out/prebid_fledge_overview/prebid_fledge_overview.png)

cc: @lukwlodarczyk @fbastello @brodrigu @drpaulfarrow

**Comment by patmmccann** [comment] 2022-04-28 18:10
closing as dupe of #7968  and #7634 #7092

**Closed by patmmccann** 2022-04-28 18:10 UTC
