### ISSUE TITLE
Inconsistent Core.js Chunk Between Prebid.js Website Download and Command Line Build Process

### ISSUE THREAD

**Issue by sivamatta94** [prebid/Prebid.js#12342] opened 2024-10-18 10:20 UTC
I'm encountering an inconsistency between Prebid.js files downloaded from https://docs.prebid.org/download.html and the files generated via the command line build process. Specifically:

When I download the Prebid.js files directly from the website, I can see only the special code changes related to bid adapters (e.g., for 33Across and Adspirit adapters). However, when I build the same set of bid adapters using the command line, the core.js chunk is different for each adapter.
I want to know if it's possible to have a unique chunk for the core.js file that remains consistent across different adapters. The reason for this request is that I need to maintain consistent header and footer code, while only the special bid adapter code changes based on the customer's session.
Here are my system details:
Gulp CLI version: 3.0.0
Gulp Local version: 5.0.0
Node version: 18.18.1
NPM version: 6.14.12
I'm also attaching pictures of the issue and system configuration for your reference. Please let me know if you need any additional information. Thank you in advance.
![Fromweb](https://github.com/user-attachments/assets/a0550a33-fa06-4acf-89a2-790c93aea639)
![usingbuild_core](https://github.com/user-attachments/assets/8f6bc3aa-6b70-4019-9eed-4c4ee2e8a593)

**Comment by patmmccann** [comment] 2024-10-21 13:52
potential dupe of https://github.com/prebid/Prebid.js/issues/10838

**Comment by patmmccann** [comment] 2024-10-21 15:13
Closing as dupe of #10838 ; which will remain open pending documentation of gulp bundle

**Closed by patmmccann** 2024-10-21 15:13 UTC
