### ISSUE TITLE
GPT interstitial support - SafeFrames

### ISSUE THREAD

**Issue by ourcraig** [prebid/Prebid.js#10593] opened 2023-10-11 07:18 UTC
## Type of issue
Bug/Feature Request

## Description
The current version of the Prebid Universal Creative does not support GPT out-of-page interstitials in a SafeFrame environment. 

The `ucTagData.pubUrl` differs from the SafeFrame origin, leading to a `postMessage` error e.g. 

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://ourcraig.github.io') does not match the recipient window's origin ('https://8d4de8f36eb4e4b3193097ff2b247e5e.safeframe.googlesyndication.com').
```

Changing the `pubUrl` to `"*"` does not resolve the issue due to the GPT interstitial creating an iframe within the SafeFrame that the Prebid Universal Creative `postMessage` does not break out of.

Would it be possible to get support for GPT out-of-page interstitials in a SafeFrame environment?

## Test page
[pbjs-instl-tests](https://github.com/ourcraig/pbjs-instl-tests)
* [standard](https://ourcraig.github.io/pbjs-instl-tests/standard) shows PUC rendering fine in a non-SafeFrame environment
* [standard-sf](https://ourcraig.github.io/pbjs-instl-tests/standard-sf) shows `postMessage` error when trying to render inside of a SafeFrame environment

## Other information
* GPT interstitial has a frequency cap of one view per user per hour -- to refresh it use `localStorage.clear()` on the test page
* GPT docs for out-of-page interstitial [here](https://developers.google.com/publisher-tag/samples/display-web-interstitial-ad)

**Comment by patmmccann** [comment] 2023-10-11 14:23
This is a dupe of #5917

**Closed** 2023-10-11 14:23 UTC
