### ISSUE TITLE
Filter with labelAll or labelAny doesn't work for media type video

### ISSUE THREAD

**Issue by ethyde** [prebid/Prebid.js#4135] opened 2019-08-30 14:03 UTC
## Type of issue
Bug

## Description
When I am in the mediatype video, I want to filter the bidders configurations according to the device using the information of sizeConfig and labelAny or labelAll.

But that does not seem to apply

## Steps to reproduce
1. add a sizeConfig with desktop, tablet or mobile
2. add 2 videos adunits, with 2 bidder config : one with `labelAny: ["desktop"]`, and one with labelAny: ["phone"]
3. load test page on any type of device, all bidder config are used

## Test page
there are some javascript errors but not related to this issue
https://jsfiddle.net/6zjpqxbf/

### Expected results
For media type Video, bidders are filtered according to the labels.

### Actual results
all bidders are send regardless of the labels

**Comment by bretg** [comment] 2019-09-04 02:20
@ethyde - in your expected results section you mention 'ad for the media type banner', but the title notes that the problem is in media type video. 

It makes sense that sizeConfig doesn't consider playersize - I suspect we never considered that scenario. But I think it should work for mediatype banner.

**Comment by ethyde** [comment] 2019-09-09 09:03
Thanks for your answer, and sorry for delay. I have updated description and expected result.

**Comment by bruceheller** [comment] 2019-10-01 15:31
Hello, we have the same issue.

**Comment by henrique-bromedia** [comment] 2022-11-17 12:33
This issue still exists, will create PR to fix it ;)

**Comment by patmmccann** [comment] 2023-05-25 03:43
closed by #9893

**Closed by patmmccann** 2023-05-25 03:43 UTC
Labels: bug, video
