### ISSUE TITLE
Pub Provided ID incorrectly labeled Prebid.js attribute?

### ISSUE THREAD

**Issue by gloeffelholz** [prebid/Prebid.js#6097] opened 2020-12-08 16:02 UTC
This page lists the attribute of Pub Provided ID as the same as the Pub Common ID which is "pubcid".  Is this correct or should this be found in "ppid"?

https://docs.prebid.org/dev-docs/modules/userId.html#id-providers

**Comment by bretg** [comment] 2020-12-08 19:14
@jdwieland8282 - does pubProvided even support `bidRequest.userId.ppid` or just the eids approach?

The issue is that the docs page has what looks to be a copy/paste error

![Screen Shot 2020-12-08 at 2 13 55 PM](https://user-images.githubusercontent.com/4412838/101530260-abaf4980-395f-11eb-9d04-6901d2905c30.png)

**Comment by jdwieland8282** [comment] 2020-12-09 21:04
Should just be the eids approach I'm not familiar with the ppid

**Comment by bretg** [comment] 2021-01-05 22:36
I dug around the code enough to determine that the correct value is bidRequest.userId.pubProvidedId. Fixed in 
 https://github.com/prebid/prebid.github.io/pull/2608

**Closed by bretg** 2021-01-05 22:36 UTC
