### ISSUE TITLE
Debug log don't return all bids

### ISSUE THREAD

**Issue by acidrainz** [prebid/Prebid.js#2393] opened 2018-04-13 00:17 UTC
## Type of issue

Debug log don't return all the bids 
## Description

Upgraded our prebid from 0.34 to 1.6.0 and notice that not all bids are returned but instead only returned the winning bids
![version 0 34 6 debug - all bids](https://user-images.githubusercontent.com/1921292/38710387-db83a63e-3ef2-11e8-958b-6dabf32fd817.png)
![version 1 6 0 - winning bids only](https://user-images.githubusercontent.com/1921292/38710419-f8119068-3ef2-11e8-86c2-28d5114a184e.png)

### Expected results
All bids should be on the debug log
### Actual results
Only winning bids or available bids are returned

**Comment by chefbenjamin** [comment] 2018-04-13 20:53
@acidrainz and @mercuryyy you need to update the snippet for the v1.0 release. the pre 1.0 version dosent work properly http://prebid.org/dev-docs/toubleshooting-tips.html#see-all-bids-in-the-console

**Comment by mercuryyy** [comment] 2018-04-13 22:08
@chefbenjamin even with the new snippet it only shows availibe bids, meaning bids that did not get a reasponse back are not shown where in 0.36 it was.

@mkendall07  Matt you asked how will this matter, well when creative size mapping and having a large adunits files seeing all bids sent even without response bad helps debugging your setup and seeing all ad sizes were requested correctly.

**Comment by chefbenjamin** [comment] 2018-04-13 22:17
@mercuryyy that is true. the old version of the snippet did show bid requests with an empty response. 

that said, I can see how multiple ad sizes might be a good debugging feature.

**Comment by Slind14** [comment] 2018-04-14 20:40
I have been using this information a lot for debugging before. It would be great if we could get access to it via. the js console again. On another matter, I never understood why this snippet was needed with 0.x, since we could just print the entire list of all bids containing no bids and errors, too.

**Comment by mkendall07** [comment] 2018-05-21 17:59
Re-opening in case someone wants to implement. Don't expect the core team will have bandwidth to tackle this though.

**Comment by mercuryyy** [comment] 2018-05-21 20:19
@mkendall07   i looked through the analytics api and i cant find anything that will return value for empty bids.

if i want to pass to analytics bids returned empty but did not timeout its not possible.
if i want to pass to analytics bids that timed out with no bid response at all not possible.

I saw many in Slack have the same concerns.

For testing adapters/bidders this is crucial, i hope you guys consider adding an option to display/hide that data in both
.getBidResponses()
.getBidResponsesForAdUnitCode(..)

**Comment by bwoolcott** [comment] 2018-10-11 21:39
I'm closing out this ticket as it's a duplicate of https://github.com/prebid/Prebid.js/issues/2640 which has resulted in the following PR https://github.com/prebid/Prebid.js/pull/3022 Please reference/comment on those two.

**Closed by bwoolcott** 2018-10-11 21:39 UTC
Labels: feature, help wanted
