### ISSUE TITLE
How to change dynamically fetched floors for refreshed auctions or enforce request to floors endpoint? 

### ISSUE THREAD

**Issue by pnhegde** [prebid/Prebid.js#8766] opened 2022-08-02 07:02 UTC
## Type of issue
Question 

## Description
When we configure dynamic floors, the endpoint will be called only on page load/refresh and subsequent refreshed auctions make use of these initial floors instead of calling the endpoint again. I believe this was intentional to avoid unnecessary calls to the endpoint. I want to apply different floors for refreshed ads and in order to enforce the dynamic floor fetch for refreshed ads, I'm pushing the floor config again to the `pbjs.que` on the `auctionEnd` event.  

Ideally, I want to make slight changes to the floor values fetched on the initial auction before applying them in the refreshed ads instead of calling the endpoint again and again for every refresh.  Is there a way to do this? 

Thanks!

**Comment by dgirardi** [comment] 2022-08-02 17:31
I think you could manually fetch floor data and call `setConfig({floors: {data: <fetch_result>}})` with it, so that on the next auction you still have that data around and can setConfig again after modifying it (if this is what you are looking to do).

We could make it easier by making that data available somehow; maybe with `getConfig('floors.data')`? I'm not sure if this would break some other scenarios so maybe we need some other access point, like `pbjs.getFloorData()`.

**Comment by patmmccann** [comment] 2022-08-02 20:13
dupe of https://github.com/prebid/Prebid.js/issues/7626

**Closed by patmmccann** 2022-08-02 20:13 UTC
