### ISSUE TITLE
Rubicon is loaded after response from other bidders

### ISSUE THREAD

**Issue by mercuryyy** [prebid/Prebid.js#545] opened 2016-08-19 14:12 UTC
Please see attached image.

First file is prebid.js
next 3 is brealtime
next 1 is sovrn 
(so fare they all started the request at the same time)
next 3 is rubicon fastlane json they start the request only after the others finish.

![screen shot 2016-08-19 at 10 02 22 am](https://cloud.githubusercontent.com/assets/7463132/17812461/31b324c2-65f5-11e6-899c-005ce6035198.png)

same response here:

![screen shot 2016-08-19 at 10 11 08 am](https://cloud.githubusercontent.com/assets/7463132/17812491/52e8e438-65f5-11e6-9a91-e8bafa3bc0a1.png)

shouldn't they all start the request at the same time? i think this might have something to do with when calling the rubicon "http://ads.rubiconproject.com/header/ACCOUNT-ID.js" file, which gets called at the same time as brealtime,sovrn

Im using latest build 0.12 (not pre) updated 1 day ago.

**Comment by bretg** [comment] 2016-08-19 19:28
The Rubicon adapter loads another library before calling the exchange -- this may be a source of delayed start compared to adapters who don't load additional code.

You may be able to improve auction timing by 'preloading' the Rubicon library higher in the page, like just after loading Prebid. e.g.

     <script src="//ads.rubiconproject.com/header/ACCOUNTID.js" async></script>

**Comment by mkendall07** [comment] 2016-08-20 16:21
agree with Bret, this is most likely caused by additional latency around loading the Rubicon library. 
@bretg 
Is removing the `account.js` dependency on your roadmap?

**Comment by mercuryyy** [comment] 2016-08-20 18:08
@mkendall07 

So i think when loading the account.js that's what loads the ad tags .fastlane .json file so i dont see how i can split this from the prebid code

setIntegration("pbjs"),window.rubicontag.run(a,o)}))}var b=window.location.protocol+"//ads.rubiconproject.com/header/",m="rubicon",v={"468x60
.....

**Comment by bretg** [comment] 2016-08-22 14:27
@mercuryyy - you're right, loading the library is required. Note that it's not just code that's loaded, but also account configuration.

It is on the roadmap to move code and config either into the server and adapter, but it will take some time for that transition.

**Comment by mercuryyy** [comment] 2016-08-22 15:08
Thank you @bretg so as for now there is no way to async load rubicon ?

**Comment by Deimos01** [comment] 2016-08-22 15:27
Hello guys,

I just move the loading of "ads.rubiconproject.com/header/XXXXX.js" in the header of my page instead of letting prebid call it.

Here the result (ignore Criteo) : 

Before
![image](https://cloud.githubusercontent.com/assets/5635647/17860230/0613a0b8-688d-11e6-80c7-c405b733d690.png)

After
![image](https://cloud.githubusercontent.com/assets/5635647/17860183/d55ba8b2-688c-11e6-929b-d2118dc87182.png)

So i don't know if it's helping but this method is working for me (v0.11.0)

Thank you

**Comment by mercuryyy** [comment] 2016-08-22 16:32
It looks good. How did you implement it in the code? Because header.js calls the account configuration for prebid settings

**Comment by mkendall07** [comment] 2016-08-22 18:21
I don't really recommend loading Rubicon outside of prebid.js because it will be requested twice in that case (although it may speed up Rubicon response).

**Comment by snapwich** [comment] 2016-08-22 22:36
@mkendall07 the rubicon adapter will detect if the rubicon code has already been externally loaded and if so will not make a second request.

**Comment by mercuryyy** [comment] 2016-08-22 23:03
@snapwich @mkendall07 

looks like loading rubicon header .js before prebid fixes a lot of latency problems and improves win rate by a good number.

For anybody testing try adding this before your prebid code and share results.

(function() {
    var bct = document.createElement('script');
    bct.type = 'text/javascript';
    bct.async = true;
    bct.src = (document.location.protocol === 'https:' ? 'https:' : 'http:') + '//ads.rubiconproject.com/header/ACCOUNT_ID.js';
    var node = document.getElementsByTagName('script')[0];
    node.parentNode.appendChild(bct);
})();

**Comment by Deimos01** [comment] 2016-08-23 09:50
@mercuryyy 

Your code is working, i will realease (today or tomorrow) the rubicon optimized version on my network and confirm if it improves really the win rate :).

I just discovered maybe there are the same problem for Pulsepoint too : 
![pulsepoint](https://cloud.githubusercontent.com/assets/5635647/17887477/015ca7b4-6927-11e6-9aa6-dbbeab8993ce.png)

I think if we load all the librairies externally, it could be a great improvement for latency and maybe the win rate.

**Comment by mercuryyy** [comment] 2016-08-23 12:15
I'v experienced a 10% increase in bid win rate for rubicon after these changed

before: 2,000,000 impressions (rubicon won 281,000)  seen this number stay the same for over 30 days

after 2,000,000 impressions (rubicon win 313,000)

Pretty significant change.  i wonder why all the libraries from adapters are not set in an ararry and loaded all together async at the top of the prebid code?

**Comment by Deimos01** [comment] 2016-08-23 14:23
Indeed, it's a great optimization for you !
I just launched my new optimized configuration. I will have a beginning of report tomorrow.

I have an other question.

Rubicon is always the longest partner to answer in my setup (like you can see in my previous picture), so i'm dependant of him to launch my adservercalls with the winner.
I think it's complicated to reduce the time of the answer so is it possible to switch the SSP adcalls priority in prebid ? Appnexus is always the first in my setup, i would like to switch with Rubicon.

Thank you !

**Comment by mkendall07** [comment] 2016-08-23 15:13
@mercuryyy 
We have talked about the idea of "pre-loading" adapter libraries before anything else to speed responses. While this sounds like a good idea, it's not ideal. The 2 main reasons we haven't pursued this are:
1) We'd prefer (and may require eventually) adapters have all their code contained within prebid (and not downloaded as a separate HTTP call)
2) Prefetching requires additional configuration and setup on the page.

Interested in hearing others thoughts on this as well

**Comment by mercuryyy** [comment] 2016-08-23 15:56
@mkendall07 
i think the addition to the win rate is well worth it.  in response to "1"
I doubt all networks will get to load all the code from prebid in the next 1-2 years, increasing the performance tho can lead to better revenue and increase in popularity and more willing to improve. 
Maybe its best to require them to update the adapters to include the code now or to use my method to async pre load their libraries.

I tried doing the same thing with The AOL library for example "https://secure-ads.pictela.net/rm/marketplace/pubtaglib/0_4_0/pubtaglib_0_4_0.js"

But it does not work in this case like it did with rubicon, now AOL is loading 300-400ms after rubicon, same problem i had before if i disable AOL i get a 3-4% increase in ad visibility and 5% better ad fill rate. so i can actually make 4-7% more money if i disable the AOL adapter.  ;/

**Comment by mkendall07** [comment] 2016-08-23 16:10
@mercuryyy 
Yes valid points. Also it's up to pubs to manage and a/b test bidders to see which perform for them. This is all very publisher specific. 

We will be taking a stronger stance on adapter performance when we release prebid 1.0.0. Expect to see more related to this soon.

**Comment by mercuryyy** [comment] 2016-08-23 16:38
True, but most publishers wont know how to optimize bidders to load at the same time, and even after i fixed rubicon there is nothing i can do about AOL loading after rubicon. its up to the ad networks to make their adapters to a fixed standard.

As it might take a one adapter (network) longer time to give a bid response so yes a/b testing bidder and dropping them is important. But when bidders load like in the attached screenshot, you can see AOL started the request 300-400 ms after the other bidders then a/b testing wont mean much here because you cant get the full picture.

![screen shot 2016-08-23 at 12 26 48 pm](https://cloud.githubusercontent.com/assets/7463132/17900580/c8472f1a-692d-11e6-93b8-c014cb31cd7f.png)

when you have:

sovrn - 200ms
rubicon 400ms
aol - 400ms

if they all loaded together prebid will end at 400ms but when aol loads 300ms after prebid ends at 700ms
this 300ms difference can result in 2-3% at fill rate and ad visibility rate change which is very significant in large scale and makes a/b testing not really valid

**Comment by bretg** [comment] 2016-08-23 17:49
@mercuryyy - may I enquire what site you're working with? Would like to get your data point on performance characteristics. (If you'd rather not give the domain here, could find it with the Rubicon account ID or email me at YmdvcnNsaW5lQHJ1Ymljb25wcm9qZWN0LmNvbQ==)

**Comment by mercuryyy** [comment] 2016-08-23 19:17
@bretg  i lost you there its not md5. email me at israelcohen2512@gmail.com

**Comment by slimkrazy** [comment] 2016-08-24 12:28
@mercuryyy 

The team at AOL are re-writing that adapter (they never created the existing one) and should have a far better one pushed to this project within the next few weeks.

**Comment by Deimos01** [comment] 2016-08-25 08:12
Hello,

Just to share the information.
After few days of running optimized version on my network, i can confirm a +10% increase of paid impressions for Rubicon.

900 000 per day => 1 000 000 per day

**Comment by mkendall07** [comment] 2016-08-26 00:10
Closing this out as it's not an issue that can be addressed by prebid core.

**Closed by mkendall07** 2016-08-26 00:10 UTC
