### ISSUE TITLE
Support for additional ortb2 properties in PrebidServer Bid Adatper

### ISSUE THREAD

**Issue by Fawke** [prebid/Prebid.js#7219] opened 2021-07-26 11:47 UTC
## Type of issue

Question

## Description
We want to add support for few additional **ortb2** fields in the request object created by the PrebidServer Bid Adapter:

- request.bcat
- request.badv
- request.site.publisher (and possibly request.app.publisher) > domain & name properties

We already support the publisher.id property, so just need to add other two fields.

I could figure out two possible ways for publishers to set this data:

First approach could be that we add them to the **ortb2** object as additional properties. Since both **badv** and **bcat** are defined in the official ortb2 [spec](https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf), this should be fine.

Example:

```(javascript)
pbjs.setConfig({
  ortb2: {
    site: {...},
    user: {...},
    badv: ['a.com', 'b.com'],
    bcat: ['IAB25', 'IAB7-39']
  }
})
```

This would require some minor changes in **validationFpdModule**.

Second approach could be that we add these two additional fields as part of **s2sConfig** object. 

Example:

```(javascript)
pbjs.setConfig({
  s2sConfig: {
     ...
     badv: ['a.com', 'b.com'],
     bcat: ['IAB25', 'IAB7-39']
     ...
  }
})
```

Personally, I'd prefer setting the ortb2 object since those additional props fit naturally to the original ortb2 spec, and can be used by other bid adapter as well, whereas, setting the s2sConfig would required some manipulation at the PrebidServer Bid Adapter.

**Comment by mkendall07** [comment] 2021-07-29 01:30
maybe @bretg has some thoughts on this one?

**Comment by bretg** [comment] 2021-07-29 13:21
I support expanding use of the ortb2 object as evidenced by this issue being a duplicate of https://github.com/prebid/Prebid.js/issues/6528   :-)

Just haven't managed to staff it -- any chance you could make that happen @Fawke ?

**Closed by bretg** 2021-07-29 13:21 UTC
Labels: question
