### ISSUE TITLE
 Missing parameters in bidAdjustment events

### ISSUE THREAD

**Issue by kir-roxot** [prebid/Prebid.js#1398] opened 2017-07-20 09:54 UTC
## Type of issue
 Missing parameters in bidAdjustment events

## Description
Event bidAdjustment even has changed in prebid v0.26.0 - it lacks AdUnitCode, timeToRespond, requestTimestamp, responseTimestamp. Also, if bidResponse is empty or has an error, bidAdjustment doesn't have a CPM parameter.

**Comment by dbemiller** [comment] 2017-07-20 13:18
Caused by some changes in #1277 and #1372. Will fix shortly.

**Comment by alex-khar** [comment] 2017-07-20 13:35
@dbemiller Our Prebid Analytics relies on this as it takes bids after bid adjustments.

**Comment by GLStephen** [comment] 2017-07-20 13:53
@dbemiller we use these parameters for PubWise analytics as well

**Comment by dbemiller** [comment] 2017-07-21 16:00
Fixed with the merge of #1399. Tenative plan is to release Prebid 0.26.1 with this fix (along with a few other things) on Monday.

**Closed by dbemiller** 2017-07-21 16:00 UTC
