### ISSUE TITLE
Upgrading from prebid version 3.27 to 4.1 not working

### ISSUE THREAD

**Issue by saileshd** [prebid/Prebid.js#5562] opened 2020-08-02 18:10 UTC
## Type of issue

Question

## Description

Prebid version 3.27 is working perfectly for us. However, when we upgrade to the version 4.0 or 4.1 or 4.11 it is not working at all.

These are the bidders we are including:

appnexus
beachfront
gumgum
ix
lkqd
oneVideo
openx
pubmatic
pulsepoint
rhythmone
rubicon
sonobi
spotx
telaria

Consent Management - GDPR
Consent Management - US Privacy
DFP Video
Supply Chain Object
User ID - Unified ID

### Expected results
The upgrade should work seamlessly.

**Comment by patmmccann** [comment] 2020-08-04 16:41
perhaps a test page would help

**Comment by jbartek25** [comment] 2020-08-06 07:17
might be the same issue as reported in https://github.com/prebid/Prebid.js/issues/5572

**Comment by mkendall07** [comment] 2020-08-11 22:12
Can you provide more details on what you are seeing vs what you are expecting?

**Comment by saileshd** [comment] 2020-08-25 03:07
@patmmccann @mkendall07  

Here are the test pages with the only difference being the 1st one uses prebid.js version 3.27 and the 2nd one uses prebid.js version 4.4.0

Test page 1 with prebid.js version 3.27 - https://a.jsrdn.com/test/saileshd/prebid/index.html?pbjs_debug=true
Test page 2 with prebid.js version 4.4.0 - https://a.jsrdn.com/test/saileshd/prebid/index2.html?pbjs_debug=true

**Comment by angelamerkelprebid** [comment] 2020-08-25 15:15
allowAuctionWithoutConsent is deprecated

**Comment by patmmccann** [comment] 2020-08-26 13:13
appears to be a duplicate of #5572

**Comment by saileshd** [comment] 2020-08-26 18:23
@patmmccann even when I removed the allowAuctionWithoutConsent=true from my config it still does not work.

**Comment by patmmccann** [comment] 2020-08-26 21:59
Try either installing a cmp or removing consent management module

**Comment by patmmccann** [comment] 2020-08-26 21:59
Or setting gdpr applies to false.

**Comment by saileshd** [comment] 2020-08-27 00:21
@patmmccann 
I'm including these 2 modules in my prebid.js download
Consent Management - GDPR
Consent Management - US Privacy

If I remove them, then how can I enable GDPR/CCPA where needed?

Also, shouldn't the configs work similar to how they work with the 3.x version?

**Comment by patmmccann** [comment] 2020-08-27 13:10
See from 5572
https://github.com/prebid/Prebid.js/issues/5572#issuecomment-680084767 ; if
you have a consent management config, you should either have a cmp, a
consent object you are passing in, or a setting that says gdpr applies
isn't true.

**Comment by saileshd** [comment] 2020-08-28 02:02
@patmmccann the config is set up at beginning of page. We won't know if the there is a cmp or not. The previous 3.x version was handling it correctly and the auction proceeded without any issues. Why is the auction aborting if there is no cmp on the page in the 4.x version?

**Comment by bretg** [comment] 2020-08-28 15:18
> Why is the auction aborting if there is no cmp on the page in the 4.x version?

Because TCF rules are enforced by default in 4.x if consentManagement config is provided. They weren't enforced in 3.x unless you turned them on.

You will need to work with your lawyers to determine how you want to handle the various scenarios. We've started to collect the different options available at https://docs.prebid.org/dev-docs/cmp-best-practices.html

Specifically, maybe this idea is worth considering:

```
If the CMP is removed in some geos, the publisher can use the presence of the __tcfapi function as a signal to set the PBJS consentManagement config
```

Or you could just turn off enforcement of certain purposes in certain geos that you and your lawyers agree upon.

**Comment by saileshd** [comment] 2020-08-28 16:36
@bretg 
Our ConsentManagement config contains both GDPR as well as USP. We can't just use the __tcpapi function. Is there a reason why the bidding aborts if the config is present but the __tcpapi function is not present? That won't work for CCPA

					"consentManagement": {
						"gdpr": {
							"cmpApi": "iab",
							"timeout": 10000,
							"defaultGdprScope": true
						},
						"usp": {
							"cmpApi": "iab",
							"timeout": 10000
						}
					}

**Comment by saileshd** [comment] 2020-08-28 18:17
@bretg this is how I worked around the issue. Is this the recommended way?

				var consentManagement = {};
				consentManagement.usp = {
					"cmpApi": "iab",
					"timeout": 10000
				};
				if (typeof __tcfapi === 'function') {
					consentManagement.gdpr = {
						"cmpApi": "iab",
						"timeout": 10000,
						"defaultGdprScope": true
					};
				}
				pbjs.setConfig({consentManagement});

**Comment by bretg** [comment] 2020-09-01 19:51
Closing this issue as duplicate of the conversation in https://github.com/prebid/Prebid.js/issues/5572

**Closed by bretg** 2020-09-01 19:51 UTC
