### ISSUE TITLE
Support FLoC cohort IDs (trial & release)

### ISSUE THREAD

**Issue by Viewtiful** [prebid/Prebid.js#6510] opened 2021-04-01 13:58 UTC
## Type of issue
**Questions**

## Description
Following the start of the trial of the FLoC feature linked to the privacy sandbox project, we would like to start to receive cohort IDs from our adapter.
1. Do you plan to support a solution for this trial period?
2. If we introduce a logic to retrieve the cohort IDs from our adapter for the trial period, do you see any issues doing so?
Example of a possible logic (partial pseudo code):

Programmatically inject the token for the trials:

```javascript
function activateInterestCohortFeature() {
  const tokenElement = document.createElement('meta')
  tokenElement.httpEquiv = 'origin-trial'
  tokenElement.content = 'TOKEN'
  document.head.appendChild(tokenElement)
}
```

If in a chrome browser and `interest-cohort` feature is available, retrieve it and then send it in the bid requests constructed in the adapter:

```javascript
const isChrome = !!window.chrome && (!!window.chrome.webstore || !!window.chrome.runtime);
if (isChrome && !!document.featurePolicy && !!document.featurePolicy.features() && document.featurePolicy.features().includes('interest-cohort')) {
  return await document.interestCohort() || {};
}
```

3. Is there a longer term plan for the support of FLoC and cohort IDs prebid side?

**Comment by patmmccann** [comment] 2021-04-01 14:02
Injecting the token is a concern,  we're injecting our own token. Multiple tokens could have unexpected behavior. 

This seems better as an rtd submodule than part of a bidder.

**Comment by ian-lr** [comment] 2021-04-01 16:30
@jdwieland8282 and I were discussing this. I'd like to suggest a slightly different implementation for the Origin period:

- Register `sharedid.org` (or another prebid.org operated domain) as a "Third Party Matching" origin on https://developer.chrome.com/origintrials/#/register_trial/213920982300098561
- Create a new module for "FLoC Origin Support"
- Support collection of FLoC IDs when this module is included via dropping 3P JS (from `sharedid.org`) or an iframe. 
- The available FLoC ID could be treated as a pseudo userID (cached locally for a limited TTL, provided in the eid array, made available to bidders) for maximum compatibility:

```"userIdAsEids": [
    {
      "source": "web.dev",
      "uids": [
        {
          "id": "3258",
          "atype": 1,
        }
      ]
    }
  ],```

Alternatively, this could be made available in `fpd` or an alternative data payload. 

Unfortunately, it seems like the rules of the 3P matching *require* injecting 3P JS or an iframe. But by supporting a standard module, it should be easier for publishers and bidders alike to participate in the trial at scale in a less error-prone process by operating against a single 3P origin token.

**Comment by patmmccann** [comment] 2021-04-01 17:19
I would prefer an implementation that allowed publishers to drop their own token, but happy if it defaults to sharedid.org token. 

I like @ian-lr 's suggestion of this being an id submodule instead of an rtd submodule, as id submodules are really just special types of data modules with a lot more stringent rules limiting their scope. I think it makes sense for all those extra rules to apply here.

**Comment by dmarti** [comment] 2021-04-01 17:22
Added a question on the FLoC repo: https://github.com/WICG/floc/issues/88

(Chrome is just using the token to check whether or not the page should be in the origin trial, so it should turn it on when it sees the first valid token and ignore the rest -- should not matter which token gets used. But it would be good to have someone from Chrome confirm this.)

**Comment by ian-lr** [comment] 2021-04-01 17:47
So maybe accept an optional token parameter to instantiate the module:

```
pbjs.setConfig({
    userSync: {
        userIds: [{
            name: "originFloc",
            params: {
              token: "3JsY2RuLmNvbTo0NDMiLCJmZW..."
            },
            storage: {
              type: "html5",
              name: "originFlocCache",
              expires: 1
            }
        }]
    }
})
```

@patmmccann would the need (if running on sharedid.org tokens) to drop 3P JS be an argument _against_ an id module?

**Comment by dmarti** [comment] 2021-04-01 18:15
**Update:** Multiple tokens will work the way that we thought. ("[Only one valid token is required to enable a trial, any other invalid tokens or non-matching tokens are ignored.](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#15-can-i-provide-multiple-tokens-on-a-page)") It is fine for more than one script on a page to inject the meta element.

**Comment by patmmccann** [comment] 2021-04-01 20:13
That's great news, if multiple tokens are harmless, my concerns above are moot

**Comment by abhinavsinha001** [comment] 2021-04-05 08:34
I am not very sure if FloC qualifies as an eid rather I recommend passing it as user segment.

Few points and feedback:
1. I understand and agree to use the existing eids for origin trial where its easier to implement and adopt in existing flow
2. We should push for adoption of floc id under `user.data.segment` as it essentially represents a group of users
3. I can definitely see segments fit better with future use cases like running deals directly on floc Ids rather than adding custom logic for specific eids (I am talking from SSP perspective here)
4. FloC algorithm / version is also key data point to ensure the analysis is not impacted by changes to algo so either append the version in ID string or pass is separately.
5. In short term we can internally populate the oRTB `user.data.segment` of fpd as well as `user.ext.eids` with floc id and gradually deprecate  this from eids after origin trials.

We have suggested Google OB team to use segments and keep it consistent across integrations , awaiting decision and some IAB standard for this as well.

Proposed oRTB structure user.data.segment & user.ext.eids format:
```
"user": {
  "data": [
    {
      "name": "chrome.com",
      "ext": {
        "ver": "chrome.1.1"
      },
      "segment": [
        {
          "id": "777454319066618"
        }
      ]
    }
  ],
  "ext": {
    "eids": [
      {
        "source": "chrome.com",
        "uids": [
          {
            "id": "777454319066618",
            "atype": 1,
            "ext": {
              "ver": "chrome.1.1"
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by patmmccann** [comment] 2021-04-06 14:57
@abhinavsinha001 the id modules can only populate eids. If you are advocating it end up in both places, we'll need some functionality in a different place. Do you have any concerns with @SKOCHERI 's PR going forward with eid's and then a followup pr could replicate the data into the other place?

**Comment by pm-harshad-mane** [comment] 2021-04-06 16:56
@SKOCHERI 's PR need not be blocked, we can make the necessary change to replicate the data in a follow-up PR.

**Comment by patmmccann** [comment] 2021-04-06 17:12
We brought this up at the IAB 2.6 meeting today, and it seemed consensus was leaning towards keeping it in eids, as it is 'an identifier with no inherent meaning' despite not being unique to an individual.

**Comment by Viewtiful** [comment] 2021-04-06 17:14
👍 Thanks a lot everyone for looking at this issue !
Indeed, for the moment using a new ID module makes more sense instead of a custom solution in each adapters wanted to opt-in and I also agree that it makes more sense as an `eid`.

One thing I am not sure, I could not find any documentation about it, if we can use a shared token to activate the trial features, what is the point to have a token by provider then if we can share one?

**Comment by pm-harshad-mane** [comment] 2021-04-06 17:14
Thank you @patmmccann for sharing the IAB meeting note.

**Comment by simontrasler** [comment] 2021-04-06 17:42
@patmmccann @abhinavsinha001 @ian-lr good points. For my 2 cents:
- The first implementation is the one we'll have to live with.
- Please don't send the same data in two places.
- To Patrick's point, `eids` is appropriate if this is 'an identifier with no inherent meaning' -- I would add, if it is relatively *transient*, so e.g., it would not be considered targetable.
- To Abhinav's point, `segments` is appropriate if this is a relatively *persistent* (and targetable) value that (obviously) represents a group of people.

**Comment by patmmccann** [comment] 2021-04-06 17:49
If the segment camp wins out, I would recommend moving this functionality from a userid submodule to https://github.com/prebid/Prebid.js/pull/6452

**Comment by abhinavsinha001** [comment] 2021-04-06 17:58
Agree for this phase and analysing data let's proceed with eids but I would recommend adding support for floc ID version. I am guessing the floc version and also will change frequently at least during the origin trial phase. @SKOCHERI can we add that to the PR ?

**Comment by simontrasler** [comment] 2021-04-06 18:24
(One more observation to my comment above, it's *possible* that the expected treatment of `segments` vs `eids` differ -- e.g., it's expected that `eids` are public and can be propagated all the way down the chain, whereas it may be expected that `segments` are private to the two parties in direct communication. If so, that would be a reason to use `eids`.)

**Comment by jdwieland8282** [comment] 2021-04-06 18:47
@SKOCHERI is OOO this week, if anyone else would like to make the proposed changes that would be really helpful.

**Comment by smenzer** [comment] 2021-04-07 07:18
this may be a really dumb question, but what is it exactly that is supposed to be sent through the bid adapters as the cohort ids? is it just the token? the [implementation as it stands today](https://github.com/prebid/Prebid.js/pull/6521/files#diff-fd1e4448520f3845a4bb543b1e14fad4e9dc41b003baaf035a40105d58c1a81bR60) is simply taking the token from the config and setting that as the "floc id", but there's discussion about [not making the token mandatory](https://github.com/prebid/Prebid.js/pull/6521#issuecomment-813625247) because it's temporary.  i guess i just don't see where any JS is being executed to pick up the interest cohorts like was in the pseudo code from this [original issue](https://github.com/prebid/Prebid.js/issues/6510#issue-848494124)

**Comment by patmmccann** [comment] 2021-04-07 13:05
@smenzer is correct that the pr is a wip,  however,  i am sure that will be fixed soon

The floc id is not the token, it is an integer that one can get with a browser api call document.getInterestCohort()

**Comment by zaniphrom** [comment] 2021-04-08 15:54
This seems relevant here https://developers.google.com/authorized-buyers/rtb/openrtb-guide#floc 

```
{
  "user":{
    "ext":{
      "floc":{
        "id":"str123",
        "type":1
      }
    }
  }
}
```

**Comment by abhinavsinha001** [comment] 2021-04-08 16:03
This format is what Google OB team is using for initial FloC tests.
I am not very convinced that we introduce a new object / extension in oRTB for FloC. So either eids or segments should be the right approach.
We have provided the same feedback to Google team as well.

**Comment by patmmccann** [comment] 2021-04-08 16:07
Seems like matching ob makes it so everyone doesn't have to do this twice

**Comment by abhinavsinha001** [comment] 2021-04-08 16:42
Agree - so ideally this should be finalized & standardized in IAB oRTB forum as soon as possible with OB's participation.
I follow up with our OB point of contact on this.

**Comment by pm-harshad-mane** [comment] 2021-04-08 16:57
Agree with @patmmccann , matching with OB will save efforts for everyone.

**Comment by abhinavsinha001** [comment] 2021-04-08 17:09
I am suggesting we save effort altogether -  by asking OB to adopt standard 🙂

**Comment by patmmccann** [comment] 2021-04-08 18:06
please report back with OB team's reaction and timing about changes they are planning to make if any

**Comment by smenzer** [comment] 2021-04-12 16:01
we're speaking in this PR mostly about bidder adapters getting access to the cohort ids, but what about other modules in prebid... analytics adapters, user id modules, rtd modules... 

should prebid core have a way to capture the cohort ids from the browser and make them available in a more generic way for any module (or publisher) to access? in this way, we don't need to figure out today how to pass them in bid requests, as that could be established later (or changed on a bidder to bidder basis as required).

thoughts?

**Comment by patmmccann** [comment] 2021-04-13 12:24
@smenzer More generic than putting it in the ortb2 object?

**Comment by smenzer** [comment] 2021-04-13 12:35
@patmmccann well, not everyone is a participant in or has access to the ortb2 object, right? bidder adapters do and i believe analytics adapters can read from the userIds, but what about rtd providers or user id modules? i'm just wondering if eids is the right "generic" place for it or if it should be it's own thing within prebid?

**Comment by patmmccann** [comment] 2021-04-13 12:40
Rtd modules can,  in fact one of their core functions is to read the object merge some data and set it again. 

Userid modules I am not sure if they can get it from that,  but just doing document.getInterestCohort() would seem to get it if you want it and I can't think of a rule that would violate.

**Comment by patmmccann** [comment] 2021-04-13 16:10
Above it seems web.dev and chrome.com are proposed as eid sources. In the PR it proposes floc.com. Can we come to a consensus?

**Comment by ian-lr** [comment] 2021-04-13 16:29
@patmmccann I'd suggest _not_ using floc.com as that domain belongs to the AFL-CIO, but don't have a strong feeling otherwise.

**Comment by smenzer** [comment] 2021-04-13 18:32
> Rtd modules can, in fact one of their core functions is to read the object, merge some data, and set it again.
> 
> Userid modules I am not sure if they can get it from that, but just doing document.getInterestCohort() would seem to get it if you want it and I can't think of a rule that would violate.

Ok understood. Then I'm good with the approach to leave it in eids for now and user id modules could grab it if they end up wanting to.

**Comment by SKOCHERI** [comment] 2021-04-14 00:31
@patmmccann @smenzer Kinda blocked with testing the FloC api. Any help or lead much appreciated.

On FloC demo(https://floc.glitch.me/) , the cohort ID and version is unavailable for chrome version 91.0.4469.4 (Official Build) dev (x86_64).
Also on the console when checking for await document.interestCohort(), I get "Uncaught DOMException: Failed to get the interest cohort: either it is unavailable, or the preferences or content settings has denied access." 

On a test page(userId_example.html), I get document.interestCohort() is not a function issue. 
Have commented the above issue in https://github.com/WICG/floc/issues/98

Also, the interestCohort() is a async function, can you guide me on how we handle this within getId()

**Comment by SKOCHERI** [comment] 2021-04-14 07:46
> @patmmccann @smenzer Kinda blocked with testing the FloC api. Any help or lead much appreciated.
> 
> On FloC demo(https://floc.glitch.me/) , the cohort ID and version is unavailable for chrome version 91.0.4469.4 (Official Build) dev (x86_64).
> Also on the console when checking for await document.interestCohort(), I get "Uncaught DOMException: Failed to get the interest cohort: either it is unavailable, or the preferences or content settings has denied access."
> 
> On a test page(userId_example.html), I get document.interestCohort() is not a function issue.
> Have commented the above issue in [WICG/floc#98](https://github.com/WICG/floc/issues/98)
> 
> Also, the interestCohort() is a async function, can you guide me on how we handle this within getId()

**Comment by SKOCHERI** [comment] 2021-04-14 07:47
Able to resolve these issues
> @patmmccann @smenzer Kinda blocked with testing the FloC api. Any help or lead much appreciated.
> 
> On FloC demo(https://floc.glitch.me/) , the cohort ID and version is unavailable for chrome version 91.0.4469.4 (Official Build) dev (x86_64).
> Also on the console when checking for await document.interestCohort(), I get "Uncaught DOMException: Failed to get the interest cohort: either it is unavailable, or the preferences or content settings has denied access."
> 
> On a test page(userId_example.html), I get document.interestCohort() is not a function issue.
> Have commented the above issue in [WICG/floc#98](https://github.com/WICG/floc/issues/98)
> 
> Also, the interestCohort() is a async function, can you guide me on how we handle this within getId()

**Comment by smenzer** [comment] 2021-04-14 18:03
after discussion in the Prebid Privacy & Identity PMC, it was agreed that a user id module could be used to capture the floc id, but that it should not be added to the eids array which is more difficult to parse out. so, we'll remove the `eids.js` code from the PR.

since some ssp's may still want to pass the floc id in eids to themself, we should add a utility method to create an eids array and add the floc id, called `getUserIdsAsEidsWithFloc()`.

**Comment by pm-harshad-mane** [comment] 2021-04-14 18:33
```
{
  "user":{
    "ext":{
      "floc":{
        "id":"str123",
        "type":1
      }
    }
  }
}
```
Floc version should have been part of it, isn't it? Can we add it to an extension? example below
{
  "user":{
    "ext":{
      "floc":{
        "id":"str123",
        "type":1,
        "ext": {
            ver: "chrome1.1"
        }
      }
    }
  }
}
```

**Comment by smenzer** [comment] 2021-04-14 18:40
Yes but that's not relevant for the prebid piece, right? That's how ssps with communicate to dsps which is really outside of the scope here. Potentially relevant when we get to the FPD implementation though.

**Comment by abhinavsinha001** [comment] 2021-04-14 19:35
FloC version is important info that is provided by chrome API and potentially represents the algo used, min FloC size etc.. so should be captured in prebid module.

On the parsing overhead justification around not using existing ortb standard like segment/ eids  - I do not see how it is justified  that we invest in building a new pipe across ecosystem for ingesting this new object. 
Unless we have reached a point where we are discarding segments/ eids without even parsing/looking at them? 🤔. I hope we have some better justification behind the decision.

**Comment by JoelPM** [comment] 2021-04-14 19:35
@pm-harshad-mane are you asking about having the version attribute in the agreed upon location that @smenzer pointed out? I do agree that having access to the cohort version in the Prebid adapter makes sense and will be needed by anyone looking to conusme it.

**Comment by JoelPM** [comment] 2021-04-14 19:37
@abhinavsinha001 - it was pointed out in the Prebid & Identity PMC meeting today that where Prebid.js and ORTB put the cohort information are orthogonal. IAB should weigh in on where cohort & version get exposed in an ORTB bid request. Prebid.js should decide how that information is made available to bid adapters (but it doesn't have to be tied to an ORTB structure).

**Comment by abhinavsinha001** [comment] 2021-04-14 19:53
@JoelPM thanks for clarifying.Makes sense in the short term.

In the long term though(once we finalize where this goes in oRTB)  I feel these might not be orthogonal atleast for adapters who support oRTB standard. Instead of each adapter writing its own logic to consume and pass this it's better to have this oRTB object pre-created which can be consumed and passed as is.

**Comment by JoelPM** [comment] 2021-04-14 20:18
Fair point @abhinavsinha001. There's probably a larger conversation to be had about how much Prebid.js wants to encourage adapters to move in the direction of ORTB. I know the [Prebid.less](https://github.com/prebid/Prebid.js/issues/5001) proposal didn't go anywhere a year ago, but it had some principles that I think are worth revisiting (though that's wildly out of scope for this issue).

**Comment by patmmccann** [comment] 2021-04-23 16:19
#6521 looks ready to merge, does anyone have any remaining comments before this goes into 4.37?

**Comment by patmmccann** [comment] 2021-05-05 20:04
This is merged, thanks @Viewtiful for the suggestion!

**Closed by patmmccann** 2021-05-05 20:04 UTC
