### ISSUE TITLE
Upgrade Node.js for currency conversion lambda functions

### ISSUE THREAD

**Issue by bretg** [prebid/Prebid.js#11726] opened 2024-06-06 19:26 UTC
## Type of issue
Upgrade Node.js for currency conversion lambda functions

## Description
We have a couple of AWS Lambda functions that refresh and monitor the currency conversion file.

Lambda is soon going to deprecate the version of Node.js we're using, so we need to upgrade at some point in the next few months. This "should" be relatively easy as these are not terribly complicated scripts, but last time we did this there was a change we had to make, so who knows.

**Comment by patmmccann** [comment] 2024-06-18 14:39
dupe of https://github.com/prebid/Prebid.js/issues/10887

**Closed by patmmccann** 2024-06-18 14:39 UTC
