### ISSUE TITLE
Prebid server adapter: consent information missing + conflict with site/app object

### ISSUE THREAD

**Issue by JulieLorin** [prebid/Prebid.js#9333] opened 2022-12-13 14:31 UTC
## Type of issue
This is a bug

## Description
We are using prebid server adapter and I think PR #8738 introduced a few bugs for us
We are settings the app object through pbjs.setConfig, and also an accountId in s2sConfig. With this setup, prebid server adapter will generate a request with both app object (from pbjs config) and site object (with the accountId from s2sConfig as publisher) which will be refused by prebid-server (because both app and site objects are defined)
Also, it seems that the consent is no longer sent to prebid-server. I noticed in the pull request all this code being deleted from prebid server adapter, but no mention of consent is made in the new ortbConverter file : 
![image](https://user-images.githubusercontent.com/635021/207358031-191fe1c3-6680-46de-a6b4-1f91b9e99a7b.png)

## Steps to reproduce
Setup an app object and s2sconfig with an accountId => pbs adapter will generate a request with both app and site objects
We setup consent ourself using `gdprDataHandler.setConsentData(consentData)` and this works fine for all adapters, but no consent is present in the request generated by prebid server adapter

**Comment by bretg** [comment] 2022-12-13 15:05
The app/site aspect is related to issue https://github.com/prebid/Prebid.js/issues/7329

**Comment by dgirardi** [comment] 2022-12-13 16:41
Could you provide steps to reproduce for the missing consent? (the logic has been moved [here](https://github.com/prebid/Prebid.js/blob/182f08e314cb1d7ab9a5fc6cf86ed0179684474b/modules/consentManagement.js#L359))

**Comment by JulieLorin** [comment] 2022-12-13 16:57
> Could you provide steps to reproduce for the missing consent? (the logic has been moved [here](https://github.com/prebid/Prebid.js/blob/182f08e314cb1d7ab9a5fc6cf86ed0179684474b/modules/consentManagement.js#L359))

Simply enable s2sConfig on some bidders, then set a gdprConsent using `gdprDataHandler.setConsentData` then run an auction (pbjs.requestBids).
There won't be any consent data in pbs payload : 
![image](https://user-images.githubusercontent.com/635021/207395669-58b46aa7-7f87-426b-8ecd-e6574831949e.png)
The function `setOrtbGdpr` is not called

**Comment by dgirardi** [comment] 2022-12-13 17:47
The first issue - malformed requests with both app and site - should be fixed with https://github.com/prebid/Prebid.js/pull/9258

**Comment by JulieLorin** [comment] 2022-12-13 17:51
> Are you working off a fork then? or how are you getting access to `gdprDataHandler`?
> 
> The ortbConverter changes were done assuming that consent would be set through the consent module. If you are doing something else, a workaround is to `setConfig({ortb2: { / * regs and user.ext.consent */ }})` instead or in addition to calling gdprDataHandler. Please do let me know if I missed a public access point to the consent handler objects.

We are working with prebid.js as a npm dependancy which allows us to get access to `gdprDataHandler`.
Thanks for the explanation (and for the coming fix), the workaround should do the trick for us !

**Comment by dgirardi** [comment] 2022-12-13 17:59
I did miss the npm access! I'll have to think about it more, but for now, use anything that's not under the `pbjs` global at your own peril. I don't think it's feasible to keep compatibility with everything else, because it's a _lot_.

**Closed** 2023-01-25 18:48 UTC
