### ISSUE TITLE
Consumable Bidder - Killing publisher's traffic.

### ISSUE THREAD

**Issue by smartbidder1** [prebid/Prebid.js#3541] opened 2019-02-08 16:08 UTC
## Type of issue
uite a shady bidder.

## Description
A few weeks ago, and we've noticed some strange fluctuation in terms of CPM drops all over the place.
After a deep investigation, we have found out that it happened right after we've added Consumable bidder as one of our bidders.

It turns out that this line in the bidder:
`ad += '<script type=\'text/javascript\'>document.write(\'<scr\'+\'ipt type=\"text/javascript\" src=\"https://yummy.consumable.com/' + unitId + '/' + unitName + '/widget/unit.js?cb=' + cb + '\" charset=\"utf-8\" async></scr\'+\'ipt>\');</script>'`

Is adding a script to the returned bid, which in return, is doing ad rotating, and refreshing the ad unit each 10 seconds, without the publisher knowledge.
It seems that they are setting up a new DFP inside the ad, and they are doing an internal header bidding inside the ad itself.

It is known that SSP's often have a limit of BIDS that they return/render to a specific user/IP, and Consumable bidder is causing the SSP's to reach those limits, and practically paying to publisher X CPM in order to later drain his traffic for any income that they can do from squeeze that single impression. 

here is a link to a video showing this in action on a QA environment:
https://www.zeta-uploader.com/1969851554

@naffis 

My only hope that this is something that prebid can resist and that the bidder would be fixed soon.

**Comment by naffis** [comment] 2019-02-08 16:15
What site is this on? This intended behavior and should have been explained and demonstrated during the sales process. The consumable content unit displays content and ads in tandem, although the timing of yours seems to be misconfigured or a bug. Please reach out to your consumable rep to discuss and fix.

**Comment by smartbidder1** [comment] 2019-02-08 16:26
If those were just consumable ads units that behavior was fine.
But you are also doing countless of hidden header bidding auctions inside the ad itself querying again and again each 10 seconds for a bid from Appnexus and the largest SSP's, causing they "maximum bids per UUID" limit to be reached and hurting the publisher itself!

![image](https://user-images.githubusercontent.com/30568117/52491083-f084c080-2bce-11e9-97a9-eb4574a7cd52.png)

**Comment by naffis** [comment] 2019-02-08 16:32
Yes, our unit makes client-side call to our SSPs to fill. We can switch your unit to make a server-side call. There should be a handful of calls during each request cycle. Please reach out and we can resolve the behavior. These issues would be more easily and quickly addressed through your Consumable rep as opposed to this forum.

**Comment by mkendall07** [comment] 2019-02-08 17:49
closing this as it's better handled offline with the SSP. Thanks

**Closed by mkendall07** 2019-02-08 17:49 UTC
