### ISSUE TITLE
gulp test-coverage not working with computer hardware

### ISSUE THREAD

**Issue by Skylinar** [prebid/Prebid.js#7694] opened 2021-11-10 10:46 UTC
## Type of issue

bug

## Description

I have cloned the repository and tried to make a build, but `gulp build` is failing since 6.0.0 release. Any hints whats wrong?

## Steps to reproduce

Clone the repository
Make sure you have gulp-cli installed as a global package. Install it if you don't.
Run `npm ci`
Run `gulp build`

### Actual results
```
gulp build
[11:36:51] Using gulpfile ~/Development/Projects/Prebid.jsNew/gulpfile.js
[11:36:51] Starting 'build'...
[11:36:51] Starting 'clean'...
[11:36:51] Finished 'clean' after 74 ms
[11:36:51] Starting 'build-bundle-prod'...
[11:36:51] Starting 'makeWebpackPkg'...

WARNING (@babel/preset-env): We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

More info about useBuiltIns: https://babeljs.io/docs/en/babel-preset-env#usebuiltins
More info about core-js: https://babeljs.io/docs/en/babel-preset-env#corejs
[11:37:06] Version: webpack 3.12.0
                             Asset     Size  Chunks                    Chunk Names
         byDataAnalyticsAdapter.js  78.3 kB       0  [emitted]         byDataAnalyticsAdapter
                             [...]                             [...]                             [...]

WARNING in EnvironmentPlugin - LiveConnectMode environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.
[11:37:06] Finished 'makeWebpackPkg' after 14 s
[11:37:06] Starting 'bound gulpBundle'...
[11:37:06] 'bound gulpBundle' errored after 101 ms
[11:37:06] TypeError: gutil.log is not a function
    at bundle (/Users/xxx/Development/Projects/Prebid.jsNew/gulpfile.js:229:9)
    at gulpBundle (/Users/xxx/Development/Projects/Prebid.jsNew/gulpfile.js:188:10)
    at bound (domain.js:426:14)
    at runBound (domain.js:439:12)
    at asyncRunner (/Users/xxx/Development/Projects/Prebid.jsNew/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[11:37:06] 'build-bundle-prod' errored after 14 s
[11:37:06] 'build' errored after 14 s
```

## Platform details

`npm -v && node -v && gulp -v`
8.1.0
v12.16.1
CLI version: 2.3.0
Local version: 4.0.2

**Comment by ChrisHuie** [comment] 2021-11-10 14:22
@Skylinar have you pulled in a recent version of master or just tried it specifically on the 6.0 branch. There was a pr shortly after that fixed a problem with which browsers were being transpilled. The other possibility is that with a newer version of npm it looks like node_modules are being installed recursively under the plugins folder. If commenting out this line https://github.com/prebid/Prebid.js/blob/fc9caa281f4e1a3ab841198b834db8700755a819/gulpfile.js#L78 fixes it that is the problem.

**Comment by ChrisHuie** [comment] 2021-11-10 18:28
A fix for the plugins issue is also currently on master right now and will be in 6.1 release

**Comment by Skylinar** [comment] 2021-11-11 10:24
@ChrisHuie thanks for the hint, I was checking out the 6.0 branch and not master, now with latest on master `gulp build` runs as expected. Another problem seems to occur now with `gulp test-coverage`:

```
gulp test-coverage
[11:08:40] Using gulpfile ~/Development/Projects/Prebid.js2/gulpfile.js
[11:08:40] Starting 'test-coverage'...
[11:08:40] Starting 'clean'...
[11:08:40] Finished 'clean' after 20 ms
[11:08:40] Starting 'testCoverage'...
11 11 2021 11:08:40.151:WARN [karma-server]: Passing raw CLI options to `new Server(config, done)` is deprecated. Use `parseConfig(configFilePath, cliOptions, {promiseConfig: true, throwErrors: true})` to prepare a processed `Config` instance and pass that as the `config` argument instead.

START:
⚠ ｢wdm｣:
ℹ ｢wdm｣: Compiled with warnings.
ℹ ｢wdm｣: Compiling...

WARNING (@babel/preset-env): We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

More info about useBuiltIns: https://babeljs.io/docs/en/babel-preset-env#usebuiltins
More info about core-js: https://babeljs.io/docs/en/babel-preset-env#corejs

<--- Last few GCs --->

[11799:0x10296a000]   150004 ms: Mark-sweep 2041.2 (2051.4) -> 2040.5 (2051.7) MB, 2127.6 / 0.0 ms  (average mu = 0.083, current mu = 0.001) allocation failure scavenge might not succeed
[11799:0x10296a000]   151305 ms: Mark-sweep 2041.5 (2051.9) -> 2040.8 (2051.9) MB, 1296.8 / 0.1 ms  (average mu = 0.052, current mu = 0.003) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x100950919]
Security context: 0x12c9623408d1 <JSObject>
    1: SourceMapGenerator_addMapping [0x12c9979ef9c1] [/Users/xxx/Development/Projects/Prebid.js2/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:~103] [pc=0x173394a1bd5f](this=0x12c9c04ffe01 <SourceMapGenerator map = 0x12c9d33b4199>,0x12c9b2c2c6b9 <Object map = 0x12c9d33b3659>)
    2: /* anonymous */ [0x12c90a9832a9] [/...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20211111.111111.11799.0.001.json
Node.js report completed
 1: 0x100080c68 node::Abort() [/usr/local/bin/node]
 2: 0x100080dec node::errors::TryCatchScope::~TryCatchScope() [/usr/local/bin/node]
 3: 0x100185167 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100185103 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x10030b2f5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x10030c9c4 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 7: 0x100309837 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x1003077fd v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x100312fba v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x100313041 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x1002e035b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
12: 0x100618718 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x100950919 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
14: 0x173394a1bd5f
15: 0x173394a1ca07
[1]    11799 abort      gulp test-coverage
```

As for the `gulp build` problem, `gulp test-coverage` ran before without any problems. Any hints?

**Comment by ChrisHuie** [comment] 2021-11-15 21:11
Someone else has reported a similar issue but currently on master, gulp test-coverage is running normally for me 🤔

**Comment by Skylinar** [comment] 2021-11-17 14:56
Getting the same issue on `master` today. Where did you saw the same report? Can't find it atm.

The only workaround I found is to use manually this command to increase the memory limit for nodeJS:

`export NODE_OPTIONS=--max_old_space_size=4096`

After that, `gulp test-coverage` is running smoothly.

Do you @ChrisHuie or someone else has and idea how to increase the limit globally for Prebid.js project?

**Comment by ChrisHuie** [comment] 2021-11-18 12:12
@Skylinar so this is a computer architecture thing and believe only impacts specific systems. That is why we had another engineer have this problem but I was never able to reproduce this. Will update the gulp job to fix.

**Comment by Skylinar** [comment] 2021-11-18 16:26
@ChrisHuie any idea where to place the command within prebid.js project? That command should do the trick or what do you think?

Here I found the workaround for reference:
https://stackoverflow.com/questions/56982005/where-do-i-set-node-options-max-old-space-size-2048

**Closed** 2021-12-20 09:43 UTC
Labels: bugfix
