### ISSUE TITLE
Cookie _pbjs_userid_consent_data

### ISSUE THREAD

**Issue by thomasmasereel** [prebid/Prebid.js#6386] opened 2021-03-05 10:16 UTC
Hello,
We noticed the cookie _pbjs_userid_consent_data being stored on our properties, whereas IAB TCF v2 consent string doesn't allow it. 
You can see the behaviour on https://www.linternaute.com/, french ip, deny all through the CMP.
I understand it is linked to prebid user id module and the name mention consent data.
Could you document more precisely on this cookie : purposes, content, description etc.
Thank you

**Comment by smenzer** [comment] 2021-03-05 10:50
Hi @thomasmasereel - this cookie is used to know if the user's consent choices have changed since the last page load. It is a hashed (`cyrb53Hash`) value of the consent string with a 30 day expiration. The use case is as follows:
- user visits the site and allows all vendors when first prompted.
- user then changes their consent preferences
- user visits another page on the site. at this point, it is important to refresh the user id's in case the relevant consent for those vendors have changed and they can issue a new ID (if applicable) or return a "no-consent" signal so that the ID is no longer available.

**Comment by thomasmasereel** [comment] 2021-03-05 11:04
Thank you for your quick answer @smenzer.
Could a note added to prebid.org, in the user id module section, be considered ?
As for EU country, every cookie stored in a non consent environnement is being closely and carefully monitor.

**Comment by smenzer** [comment] 2021-03-05 11:19
I think that's probably reasonable - @bretg / @patmmccann what do you guys think? (cc'ing you both b/c there have been other discussions about prebid setting cookies)

**Comment by patmmccann** [comment] 2021-03-18 23:07
this seems closely related to https://github.com/prebid/Prebid.js/issues/6289 . I personally don't get the idea that prebid.js needs consent to write cookies. Publishers can write cookies such as this so that their site works properly, and prebid is a part of their site, deployed by them. This is a part of how prebid functions. I cannot envision a scenario where a regulator objects to this cookie, as publishers using prebid set it to better comply with the law, similar to how a cmp sets values related to consent. 

However, if others disagree, I suppose one could check to make sure prebid vendor id has purpose 1 consent, but I think that should not be the default behavior, as prebid in this case is not setting the cookie like it does in the sharedid sennse, the publisher is. 

I think it makes sense to document this at https://docs.prebid.org/dev-docs/modules/userId.html#how-it-works so anyone looking for this string on our documentation finds the explanation easily. This probably should have been done with https://github.com/prebid/Prebid.js/pull/5451

**Comment by smenzer** [comment] 2021-03-19 08:17
I agree with everything you said, @patmmccann - and yea, my bad, I should have documented it as part of #5451.

**Comment by patmmccann** [comment] 2021-03-19 16:19
@smenzer does that mean there is a docs pr we can point OP to and close the issue?

**Comment by smenzer** [comment] 2021-03-19 16:29
@patmmccann no pending docs PR, but I will put one in probably next week (unless someone else wants to volunteer!). once that's in i think we can close this out (I'll take care of that after linking the PR)

**Comment by PascalSalesch** [comment] 2021-04-07 13:47
@patmmccann atleast in germany the legal situation is that every cookie needs consent (regardless of the value or purpose).
Not because of GDPR but because of an EuGH judgement (case C-673/17 - Planet49)

I get that it's not reasonable to make it the default behavior but shouldn't it atleast be configurable?

**Comment by patmmccann** [comment] 2021-04-07 13:52
I don't get it,  this cookie literally stores the consent. It is not a third party cookie but it enables the publisher to comply with the law, similar to how one might store "opt out" as a cookie.  How are opt outs to function if one can't store them?

**Comment by smenzer** [comment] 2021-04-08 12:02
@patmmccann I generally agree with you...but I wonder if we just move the code that reads and writes the consent hash until after the gdpr checks?

what if we move https://github.com/id5io/Prebid.js/blob/master/modules/userId/index.js#L487-L488 until just after this block https://github.com/id5io/Prebid.js/blob/master/modules/userId/index.js#L490-L495 ?

**Comment by patmmccann** [comment] 2021-04-08 12:45
Seems like that would work to me as well

**Comment by smenzer** [comment] 2021-04-08 13:39
i put in a PR that may help here: https://github.com/prebid/Prebid.js/pull/6551

**Closed** 2021-05-10 09:14 UTC

**Comment by bretg** [comment] 2023-01-24 16:56
This fix doesn't work, at least in the case where the CMP is loaded after PBJS. 

See https://www.eniro.se/?pbjs_debug=true -- there are two issues on a page that we'd like to explore. Here's how to reproduce the issue:

1) either be in the EEA or VPN into the EEA
2) delete your cookies for eniro.se
3) Don't answer the CMP (AVBÖJ is deny consent, GODKÄNN is grant consent)
4) Check your cookies for the domain

### Issue 1: The _pbjs_userid_consent_data cookie is set
Setting this cookie seems counter to what this this issue was about.

I believe it's set because userId/index.js calls setStoredConsentData before GDPR check in initSubmodules. A comment there says:
```
// we always want the latest consentData stored, even if we don't execute any submodules
```
Because consentData is null, the default data stored with the _pbjs_userid_consent_data cookie assumes `gdprApplies: false`

### Issue 2: The sharedId PublisherCommonId cookie is set

Not sure exactly how this is supposed to work but a couple of observations:

- sharedId has VENDORLESS_GVLID
- the hasPurpose1Consent function returns `true` when consentData is null


### Debugging tip

You can set up Requestly (or another redirection tool) to redirect the load of https://ads.rubiconproject.com/prebid/14110_Eniro_se.js to https://ads.rubiconproject.com/prebid/14110_Eniro_se-unmin.js

The Prebid.js portion of the file being unminified helps when you're trying to set a breakpoint.

**Comment by dgirardi** [comment] 2023-01-24 17:36
on Issue 1: https://github.com/prebid/Prebid.js/pull/6551/files#r1085664042 . It could be updated to skip writing the cookie, but:

on Issue 2: pubCommonId together with several other instances where core writes to storage are not affected by gdpr enforcement unless [`strictStorageEnforcement` is set](https://docs.prebid.org/dev-docs/modules/gdprEnforcement.html). This was discussed in https://github.com/prebid/Prebid.js/issues/8651
