### ISSUE TITLE
Prebid crashes with "Uncaught URIError: URI malformed" when URL contains some words in querystring

### ISSUE THREAD

**Issue by lanceloti** [prebid/Prebid.js#5314] opened 2020-05-28 15:51 UTC
## Type of issue
Bug

## Description
Prebid crashes with "Uncaught URIError: URI malformed" when URL contains some words in querystring

## Test page
Any page containing this querystring for example: 
https://www.apolo11.com/efemerides.php?uf=RS&cidade=RS+-+Salto+do+Jacu%ED

## Platform details
Prebid 3.21 using sample script https://acdn.adnxs.com/prebid/not-for-prod/1/prebid.js

![Screenshot_293](https://user-images.githubusercontent.com/17436827/83163831-de8ba180-a0e1-11ea-99ac-c43a6aec4fd4.png)

**Comment by jsnellbaker** [comment] 2020-05-28 17:34
I think the issue is tied to the `%ED` at the end of the query string.  That doesn't appear to be a normal encoded character.  Is that part correct, or was it somehow a typo?

**Comment by lanceloti** [comment] 2020-05-28 20:03
@jsnellbaker you are right. Think the ploblem is that this site doesn't use utf-8.

**Comment by jsnellbaker** [comment] 2020-06-01 14:37
Hi @lanceloti 
I'm going to close this issue for now, since it appears to be a site-based issue rather than Prebid.js specific.  Please let us know if there are any further questions/concerns on this topic.

**Closed by jsnellbaker** 2020-06-01 14:37 UTC
