### ISSUE TITLE
client-side adapter code should not be required for server-side bidders

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#6388] opened 2021-03-05 13:01 UTC
I just updated to 4.29.0   from the download page UI and I don't think "prebid server" is being included in the download?  client side bidders work ok, but nothing/ zip for "auction"

![DevTools_-_ads_vsvl_co_uk_pub000020_scripts_AMPTEST4_29_0_html_and_Download_Prebid_js_for_Header_Bidding](https://user-images.githubusercontent.com/8503167/110118883-ebe16500-7db2-11eb-8452-3026fb8bd434.png)

**Comment by bretg** [comment] 2021-03-05 17:27
@spormeon - download of the pbsBidAdapter works for me.

 search for a string in your package known to be within an adapter like "Incorrect or unavailable prebid server default vendor option"

What's the last version you were on? There've been a few changes in the pbsBidAdapter but nothing that should be backwards compatibility breakin. There is one bug in aliases that might affect behavior - see https://github.com/prebid/Prebid.js/issues/6336

**Comment by spormeon** [comment] 2021-03-05 17:33
i was on 4.20 before ( my "live" instances are on this), I tried 4.28 as well, and seeing same result,  its throwing a big chunk of warnings,  its exactly the same setup as on "live" instances:

![DevTools_-_ads_vsvl_co_uk_pub000020_scripts_AMPTEST4_29_0_html](https://user-images.githubusercontent.com/8503167/110151824-d717c800-7dd8-11eb-8aee-bbfaa04f2795.png)

**Comment by spormeon** [comment] 2021-03-05 18:06
hang on, have you now got to also include the actual adapters of each of the bidders?

**Comment by bretg** [comment] 2021-03-05 18:08
I've seen this message recently. It means your PBJS package doesn't have these bidders in them. Please verify your download/build of the package worked properly.

**Comment by spormeon** [comment] 2021-03-05 18:09
i'm only adding the adapters of the bidders that are "client" side, as before when using prebid server you didn't have to included the adapters of the prebid server bidders

**Comment by bretg** [comment] 2021-03-05 18:11
> before when using prebid server you didn't have to included the adapters of the prebid server bidders

I thought it's been that way forever, which is why I recently opened the issue [Remove requirement for client-side adapter to run server-side](https://github.com/prebid/Prebid.js/issues/6361)

@ChrisHuie, please hunt down what changed here?

Without the adapter code, PBJS doesn't know the mediatypes, permanent aliases, or GVL ID.

**Comment by spormeon** [comment] 2021-03-05 18:34
if i build with the server side bidders adapters included, it works.  I've built without the s2s adapters being included for months back and it worked fine.  To keep the file size as small as possible, now I have to "bloat" it back up again.

**Comment by terrapop** [comment] 2021-03-11 17:52
Just to clarify for a newby: Is it required to add the vendor adapters in addition to the "Prebid Server" module for the ones that we only request bid via S2S or not? We always added them, but now I read here it's not. Confusing.

**Comment by bretg** [comment] 2021-03-11 18:07
@terrapop - the goal is that client-side code should not be required to run an adapter server-side. Currently it is.

**Comment by terrapop** [comment] 2021-03-11 19:18
Thank you for the clarification @bretg, so we're doing it correctly then.

**Comment by bretg** [comment] 2021-03-18 19:21
We discussed in PBJS meeting yesterday -- @snapwich is going to take a look at webpack to see if there's a way to surface just the aliases, mediatypes, and gvl IDs when an adapter is server-side

**Comment by gglas** [comment] 2021-04-12 15:24
@snapwich were you able to take a look at this?  I will also add to this week's PMC.

**Comment by snapwich** [comment] 2021-04-12 15:46
@gglas i did some investigation and commented in https://github.com/prebid/Prebid.js/issues/6361

I think this ticket is probably a duplicate?

**Comment by ChrisHuie** [comment] 2021-05-24 15:44
closing as duplicate of #6361

**Closed by ChrisHuie** 2021-05-24 15:44 UTC
