### ISSUE TITLE
Feature request: allow changing `globalVarName` from the prebid.org download page

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#8912] opened 2022-08-29 15:56 UTC
I'm tetsing out V7 but I think there is a IX CORS error being thrown since the new endpoint in 6.29.0.  When I use 6.25.0 (what I use in production) there is no error as the old endpoint, but if i try 6.29.0 and/ or 7.12.0  i get this cors error:

6.29.0:
![DevTools_-_ads_vsvl_co_uk_VideoDemo_videofloat_html](https://user-images.githubusercontent.com/8503167/187242170-f983dd38-29c8-40ad-b8d2-1f7b3bcb899d.png)

7.12.0
![DevTools_-_ads_vsvl_co_uk_VideoDemo_videofloat_html](https://user-images.githubusercontent.com/8503167/187243010-eeaeccee-4716-4936-8212-b715ccb72ea1.png)

makes everything imposible to test before "upgrading" as it blocks/ breaks the IX calls

its throws error: 0, which actually not even in the IX adapter js file

**Comment by dgirardi** [comment] 2022-08-29 16:07
Could you provide a test page? the endpoint you show there does not match the endpoint in source:

https://github.com/prebid/Prebid.js/blob/fb8c62fd37d6992dbb4b1d9035adfbc943ddf293/modules/ixBidAdapter.js#L32

Is something on your end doing a search-and-replace of `pbjs` ?

**Comment by spormeon** [comment] 2022-08-29 16:09
i've actually just found what it is, the endpoint includes pbjs, so , as we chnage the global to another global it changes the endpoint /pbjs.  So for anyone that chnages the global, this is a problem

**Comment by dgirardi** [comment] 2022-08-29 16:18
Changing the global,  `globalVarName` in either `package.json` or Babel configuration, should not affect this, and doesn't for me. Could you provide steps to reproduce?

**Comment by spormeon** [comment] 2022-08-29 16:19
we always download the prebid version from the download page, simple find and replace in the file, find pbjs, replace with XXXX

**Comment by dgirardi** [comment] 2022-08-29 16:26
It seems incredible to me that doing that worked until 6.25, in fact I'd bet you must have other, probably less frequent, bugs because of it. The download page afaik does not support renaming the global variable. If you build it yourself you can rename it by manipulating `globalVarName` in `package.json`. I don't know the history behind this feature so I'm not sure if there are other more accessible options to do this.

**Comment by spormeon** [comment] 2022-08-29 16:27
it works fine, until someone decides to use pbjs for an endpoint

**Comment by dgirardi** [comment] 2022-08-29 16:34
It's not just endpoint, it's any use of that name that survives the minifier - configuration/bid params, query params, payload property names... there are more than 400 uses across all modules, it takes an alignment of planets to dodge all of them. 

I'll mark this as a feature request for the download page, but unfortunately there's not feasible way to make a manual find-and-replace work for this purpose.

**Comment by spormeon** [comment] 2022-08-29 16:37
find and replace does work, been using it for years, its juts this endpoint of /pbjs, that breaks anything.  Are you on the slack adops group, can show you test page there if want

**Comment by dgirardi** [comment] 2022-08-29 16:42
Sorry, but what you really mean is that for years you have not immediately noticed an obvious bug after doing search-and-replace on the bundle. It's possible that your combination of modules really was only affected by the recent endpoint change by ix, it becomes less and less likely the more modules you use or the more time passes. For now the fix is to build a custom bundle changing `globalVarName`.

**Comment by spormeon** [comment] 2022-08-29 16:43
no, what i really mean, is it has worked for years, full stop

**Comment by patmmccann** [comment] 2022-08-29 16:46
We don't intend for it to continue to work. https://docs.prebid.org/dev-docs/faq.html shows how to change the global correctly, but that requires building.

**Comment by patmmccann** [comment] 2022-08-29 16:51
Closing as 'won't fix'

David: that this has worked is bizarre to us, we recommend you stop this practice immediately.

**Closed by patmmccann** 2022-08-29 16:51 UTC
Labels: feature
