### ISSUE TITLE
ID Import Library

### ISSUE THREAD

**Issue by jdwieland8282** [prebid/Prebid.js#11711] opened 2024-06-05 19:28 UTC
## Type of issue
feature request

## Description
Please modify the following event listeners to `onSubmit` within the ID Import Library
1. onFocuse
2. onBlur 

## Steps to reproduce
https://github.com/prebid/Prebid.js/blob/master/modules/idImportLibrary.js

### Expected results
emails should not be captured during any event other than `onSubmit`

**Comment by patmmccann** [comment] 2024-06-05 23:21
dupe of #11708

**Closed** 2024-06-05 23:21 UTC
