### ISSUE TITLE
How to use the currency module in Prebid ? 

### ISSUE THREAD

**Issue by ShashankSureshMindEra** [prebid/Prebid.js#2756] opened 2018-06-21 10:33 UTC
## Type of issue
QUESTION: 
I have included the currency module into my script but I am not able to see it work in any way. I have tried using debuggers in place but still no effect. Is there something else I need to include to make it work ? Any help will be greatly appreciated. 

## Test page
http://boxrec.com/?pbjs_debug=true

### Expected results
Would like to see how currency module works in Prebid JS. 

## Platform details
Prebid JS v1.11.0

## Other information
https://github.com/prebid/Prebid.js/blob/1.11.0/modules/currency.js

**Comment by ShashankSureshMindEra** [comment] 2018-06-22 09:23
Anyone ?

**Comment by ShashankSureshMindEra** [comment] 2018-06-22 11:35
@YOzaz Thank you so much for extending your help.

I am at present trying to find out where the pbjs config file resides in my repo.

**Comment by ShashankSureshMindEra** [comment] 2018-06-22 11:49
<img width="497" alt="screen shot 2018-06-22 at 5 18 58 pm" src="https://user-images.githubusercontent.com/39624042/41775149-67bd92f2-7640-11e8-868a-86184ab8c913.png">

@YOzaz does this help you ?

**Comment by YOzaz** [comment] 2018-06-22 11:55
@ShashankSureshMindEra yes, ok - this means currency is enabled in config.
Now, question - is Prebid.js built with currency module included? Like this:
```
gulp build --modules=currency,bidderAdapter1,bidderAdapter2
```

**Comment by YOzaz** [comment] 2018-06-22 11:59
Ah, one more thing. `pbjs.setConfig()` should be called before `pbjs.requestBids()`.

**Comment by ShashankSureshMindEra** [comment] 2018-06-22 12:02
I checked the finally built javascript file and it looks like I can see the currency module integrated with it. 

We do not use this script to build it gulp build --modules=currency,bidderAdapter1,bidderAdapter2 instead we use gulp build-bundle-dev --modules=modules.json; 

Now, how do I know or see if this currency module is working ? Do I see any logs ?

**Comment by YOzaz** [comment] 2018-06-22 12:23
From your website I don't see currency module being injected. Does your `modules.json` file has "currency" included? E.g.:
```json
[
  "bidderAdapter1",
  "bidderAdapter2",
  "currency"
]
```

**Comment by YOzaz** [comment] 2018-06-22 12:33
Alright, then everything is as it should be. My best guess is that you're calling `setConfig()` after auction is run, so just move it above, like this:
```js
pbjs.que.push(function() {
   pbjs.addUnits(adUnits);
   pbjs.setConfig({
      currency: {
         adServerCurrency: "USD"
      }
   });
   pbjs.requestBids({
      bidsBackHandler: sendAdserverRequest
   });
});
```
Once live, you'll see debug messages like this (although it may be slightly different for pre-1.x):

![image](https://user-images.githubusercontent.com/5859318/41776733-93c39496-7631-11e8-84c0-c97aa564c2f0.png)

**Comment by ShashankSureshMindEra** [comment] 2018-06-22 12:39
Thank you so much. I have changed the order of setConfig and requestBids. 

If I attach the script I am using right now, can yo please help debug it using Resources Overrides in your local ?

**Comment by YOzaz** [comment] 2018-06-22 12:47
@ShashankSureshMindEra I'm running out of office in about 15-30 mins. But you can push it live to http://boxrec.com/?pbjs_debug=true, and we'll see if it works fine immediatelly 👍

**Comment by ShashankSureshMindEra** [comment] 2018-06-22 12:51
okay. Let me do it now. I am just worried it will affect the client's revenue.

**Comment by YOzaz** [comment] 2018-06-22 12:57
If that's the only change - it won't.
Just to note - I see you're using Prebid.js v0.32.0 with `consentManagement` module included? How's that possible?

**Comment by ShashankSureshMindEra** [comment] 2018-06-22 13:01
Sending you the updated link right now. Please give me 5 more minutes.

**Comment by ShashankSureshMindEra** [comment] 2018-06-22 13:07
[bidders-currency.txt](https://github.com/prebid/Prebid.js/files/2127715/bidders-currency.txt)

Hey I am not able to change the production version of it. Can you please help using the above .txt file as a .js file using Resources Override ? much appreciated.

**Comment by ShashankSureshMindEra** [comment] 2018-06-22 13:17
And this is v1.11.0. 

Ill check how the consent module got included in v32.0. Thank you for pointing it out :)

**Comment by YOzaz** [comment] 2018-06-22 13:20
Okay, I just did it, but don't see `pbjs.setConfig()` with `currency` property in there. Therefore nothing has changed...
In fact, I don't see `requestBids()` call in there as well - but I do see them happening here: https://static.amp.services/clients/BoxRec/Boxrec.js.
You have to investigate website source in depth, as your changes are not appearing live 👌

**Comment by ShashankSureshMindEra** [comment] 2018-06-22 13:46
You are a genius. thanks to you, I got it working now.. YOU ARE A GENIUS SIR. 👍 

<img width="920" alt="screen shot 2018-06-22 at 7 12 44 pm" src="https://user-images.githubusercontent.com/39624042/41779855-b46eda88-7650-11e8-98f1-bfb0db1b112d.png">

**Comment by harpere** [comment] 2018-06-22 19:58
@ShashankSureshMindEra  looks like the issue is solved.  closing.  reopen if necessary.

**Closed by harpere** 2018-06-22 19:58 UTC
