### ISSUE TITLE
referenced 'registerAdserver' but it was never created

### ISSUE THREAD

**Issue by aszydlo** [prebid/Prebid.js#4048] opened 2019-08-01 13:13 UTC
## Type of issue
bug/question

## Description
When I add a dfpAdServerVideo to my modules I get ``Warning`` in the console. I don't use this module in my webpage, it is only included into Prebid.js library. 
![blad-prebid](https://user-images.githubusercontent.com/38684131/62294759-ff587b80-b46b-11e9-9514-f5bdf07f0abb.jpg)

## Steps to reproduce
1. Use: gulp serve --modules=consentManagement,rubiconBidAdapter,adomikAnalyticsAdapter,dfpAdServerVideo
2. On the site with active Prebid library above described ``Warning`` is present.

## Expected results
My questions are:
Is it a bug?
How can I handle this issue?

## Platform details
I tested Prebid.js version 2.26.0, 2.25.0 only.

**Comment by jaiminpanchal27** [comment] 2019-08-01 15:08
@aszydlo Thanks for reporting this, I will check and get back to you.

**Comment by spormeon** [comment] 2019-08-02 11:35
+1, i get this as well and no idea if its something to worry about?

**Comment by snapwich** [comment] 2019-08-02 22:39
Just FYI, the warning is because the `registerAdserver` hook is defined in the `categoryTranslation` module (which isn't in your build) but is referenced in other modules such as the `dfpAdServerVideo` that are in your build.

**Comment by tandalevaibhav** [comment] 2019-10-01 11:23
I am using Prebid 2.34.0 
Getting the same warning as well as on other:- 
"fun-hooks: referenced 'registerAdserver' but it was never created"
"fun-hooks: referenced 'adpod' but it was never created"
Is there anything I should worry about ?

**Comment by jaiminpanchal27** [comment] 2019-10-02 02:28
@tandalevaibhav We have verified this and not a bug. This warning appears when an optional module is adds a hook on hook point which does not exist. 

In this case, [dfpAdserverVideo here](https://github.com/prebid/Prebid.js/blob/master/modules/dfpAdServerVideo.js#L114) is trying to add hook on [categoryTranslation here](https://github.com/prebid/Prebid.js/blob/master/modules/categoryTranslation.js#L25) but as categoryTranslation module is not included in build this warning is logged.

**Comment by gglas** [comment] 2021-02-08 16:36
assigning @robertrmartinez

**Comment by gglas** [comment] 2021-05-10 15:07
@patmmccann do the referenced PRs just relate or do the address the issue?  If they don't address, @robertrmartinez quick ping reminder on this one!

**Comment by patmmccann** [comment] 2021-05-21 10:03
#6464 fixes the issue,  awaiting merge

**Comment by gglas** [comment] 2021-07-19 15:37
merged and fixed in 5.0, closing issue

**Closed by gglas** 2021-07-19 15:37 UTC
Labels: pinned
