### ISSUE TITLE
error with adsparc

### ISSUE THREAD

**Issue by spormeon** [prebid/Prebid.js#4113] opened 2019-08-24 10:21 UTC
i get this error when adsparc in enabled:
prebid2.29.0adyjs.js:36 Uncaught (in promise) TypeError: Cannot read property 'BASE_URI' of undefined

i built prebid 2.29.0 with the adsparc adapter in it, so don't think its because thats not there?

**Comment by bretg** [comment] 2019-09-04 02:07
@aleksatr, @naegelin, @musikele - adsparc is an alias for aardvark, which you guys have touched recently.

**Comment by musikele** [comment] 2019-09-04 16:25
Hi @spormeon , can you tell me the steps to reproduce the error?

**Comment by spormeon** [comment] 2019-09-04 16:32
umm, its pretty much as simple as opening a page and maybe doing a refresh to get new bids on the page, not sure what else to tell you?

**Comment by musikele** [comment] 2019-09-04 16:34
I mean, how did you configure prebid?

**Comment by spormeon** [comment] 2019-09-04 16:36
{ bidder: 'adsparc',      labelAny: ['desktop', 'tablet', 'phone'], params: { networkId: '9969', siteId: '1019801' } }, /*one placementId for all sizes*/

**Comment by musikele** [comment] 2019-09-04 16:43
Thank you, will reach you out asap!

**Comment by musikele** [comment] 2019-09-05 14:08
Hey @spormeon I tried to replicate the issue but with no success. Here's the code i tried.

prebid: 2.29 + adsparc adapter, generated from prebidjs.org website 

index.html: the one below 
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script async src="//www.googletagservices.com/tag/js/gpt.js"></script>
    <script src="/prebid.js"></script>
    <script>
        var sizes = [
            [300, 250]
        ];
        var PREBID_TIMEOUT = 3000;
        var FAILSAFE_TIMEOUT = 8000;

        var adUnits = [{
                    code: '/19968336/header-bid-tag-1',
                    mediaTypes: {
                        banner: {
                            sizes: sizes
                        }
I'll close the ticket, feel free to reopen the ticket if you can share the code with an example that will trigger the error. 
                    },
                    bids: [{
                            bidder: 'adsparc',
                            labelAny: ['desktop', 'tablet', 'phone'],
                            params: {
                                networkId: '9969',
                                siteId: '1019801'
                            }
                        }]
                    }];

                // ======== DO NOT EDIT BELOW THIS LINE =========== //
                var googletag = googletag || {};
                googletag.cmd = googletag.cmd || [];
                googletag.cmd.push(function () {
                    googletag.pubads().disableInitialLoad();
                });

                var pbjs = pbjs || {};
                pbjs.que = pbjs.que || [];

                pbjs.que.push(function () {
                    pbjs.addAdUnits(adUnits);
                    pbjs.requestBids({
                        bidsBackHandler: initAdserver,
                        timeout: PREBID_TIMEOUT
                    });
                });

                function initAdserver() {
                    if (pbjs.initAdserverSet) return;
                    pbjs.initAdserverSet = true;
                    googletag.cmd.push(function () {
                        pbjs.setTargetingForGPTAsync && pbjs.setTargetingForGPTAsync();
                        googletag.pubads().refresh();
                    });
                }

                // in case PBJS doesn't load
                setTimeout(function () {
                    initAdserver();
                }, FAILSAFE_TIMEOUT);

                googletag.cmd.push(function () {
                    googletag.defineSlot('/19968336/header-bid-tag-1', sizes, 'div-1')
                        .addService(googletag.pubads());
                    googletag.pubads().enableSingleRequest();
                    googletag.enableServices();
                });

    </script>
</head>

<body>
    <h2>Basic Prebid.js Example</h2>
    <h5>Div-1</h5>
    <div id='div-1'>
        <script type='text/javascript'>
            googletag.cmd.push(function () {
                googletag.display('div-1');
            });

        </script>
    </div>
</body>
</html>
```

**Comment by spormeon** [comment] 2019-09-05 14:26
no error but it did bid?

**Comment by musikele** [comment] 2019-09-05 15:38
Since adsparc is an aardvark alias, you should use [Aardvark](http://prebid.org/dev-docs/bidders.html#aardvark) parameters `ai` and `sc`. So the right configuration would be 
```
{
    bidder: 'adsparc',
    params: {
        ai: 'XXXX',
        sc: 'YYYY'
}
``` 

The right values for `ai` and `sc` should be asked to adsparc.

**Comment by bretg** [comment] 2019-09-09 07:27
@musikele - the documentation for adsparc is quite different -- https://raw.githubusercontent.com/prebid/prebid.github.io/master/dev-docs/bidders/adsparc.md

@spormeon - let us know if you determine that ai and sc work. If so, someone will have to enter a PR to update the docs.

**Comment by bretg** [comment] 2019-09-16 15:21
@spormeon - the docs have been updated for adsparc. Closing this issue. Re-open if this doesn't address your issue.

**Closed by bretg** 2019-09-16 15:21 UTC
