### ISSUE TITLE
requestBids.before is not a function when running on website with old prototype.js

### ISSUE THREAD

**Issue by drdmitry** [prebid/Prebid.js#3576] opened 2019-02-21 09:32 UTC
## Type of issue

Bug

## Description

Website is using prototype.js v1.6.0.3
When Prebid v2.3.0 is used, there is an exception occures:
Uncaught TypeError: pbjs.requestBids.before is not a function

## Steps to reproduce

On the page:
Load prototype.js v1.6.0.3
Load Prebid v2.3.0
Set prebid config
Request bids

## Test page

https://jsbin.com/fiwuxuqibi/edit?html,output

### Expected results
No exception

### Actual results
Exception

## Platform details

Prebid.js 2.3.0
prototype.js 1.6.0.3

**Comment by snapwich** [comment] 2019-02-21 23:56
The issue is that the old Prototype.js library, in a horrible fashion, replaces `Array.prototype.reduce` with a version completely incompatible with `reduce` as implemented by modern browsers.  http://prototypejs.org/doc/1.6.0/array/reduce.html
vs
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

I've added an update to fun-hooks to use a `reduce` polyfill if an incompatible `Array.prototype.reduce` is detected.  You can find that here: https://github.com/snapwich/fun-hooks/commit/dade19c0653fa112666ba5639058a35b12febf69
I've also updated my current outstanding pull-request #3574 to update fun-hooks to point to this latest version so it'd contain this fix.

However, while the fix within fun-hooks was manageable and worthwhile I think (as the hope is that it can also have utilization outside of Prebid.js), the fix for the entire Prebid.js library is not trivial.  Even when #3547 is merged you'll still hit a new error `Error processing command : prebid.js TypeError: (intermediate value)(intermediate value)(intermediate value).map(...).reduce(...).filter is not a function` as well as an error any other place where `Array.prototype.reduce` is used in Prebid.js, which is around 100 different places.  Given the infeasibility of updating these `reduce` usages as well as monitoring all future code contributions for usages, I think the only solution is for you is to update your website to use a newer version of Prototype.js that is less bad (or remove the library altogether), 1.7.3.0 seems to fix your jsbin example.

**Comment by drdmitry** [comment] 2019-02-22 09:27
Unfortunately there is no access to the website. Thanks for the fix and explanation, this should be sufficient at this moment.

**Closed** 2019-02-27 15:54 UTC
