### ISSUE TITLE
CMP timeout scenario: auction without consent not running despite GDPR Enforcement Module rules

### ISSUE THREAD

**Issue by EskelCz** [prebid/Prebid.js#7156] opened 2021-07-08 11:33 UTC
## Type of issue
Bug or documentation issue

## Description
We need the auction to run even when the CMP banner stays open, relying on the "basic ads" legitimate interest. In Prebid 3 this was working with the allowAuctionWithoutConsent. In Prebid 4 and 5 I can't find a way to enable the same behavior. I've read that it should be possible by using the GDPR Enforcement module, so I have included it's configuration:
```
            defaultGdprScope: true,
            rules: [{
              purpose: 'storage',
              enforcePurpose: false,
              enforceVendor: false
            }, {
              purpose: 'basicAds',
              enforcePurpose: false,
              enforceVendor: false
            }]
```
It made no difference, with CMP banner open the Prebid triggers `cmpFailed` and stops the auction. The enforcement module code wasn't even touched, from my debugging.

Relevant logs:
- Prebid INFO: Received a response from CMP t {cmpId: 7, cmpVersion: 1, gdprApplies: true, tcfPolicyVersion: 2, eventStatus: "cmpuishown", …
...long delay
- Prebid ERROR: CMP workflow exceeded timeout threshold. Canceling auction as per consentManagement config. undefined

CMP returns event from TCF API, it gets processed with this function:
```
  function v2CmpResponseCallback(tcfData, success) {
    utils.logInfo('Received a response from CMP', tcfData);
    if (success) {
      if (tcfData.gdprApplies === false || tcfData.eventStatus === 'tcloaded' || tcfData.eventStatus === 'useractioncomplete') {
        cmpSuccess(tcfData, hookConfig);
      }
 ...
```
the second condition leaves it hanging, since eventStatus is `cmpuishown`. It doesn't look for the enforcement settings. Is this by design, or am I missing something?

## Steps to reproduce
1. Load the page with no TCFv2 consent in cookies/localStorage.
2. Prebid should wait for CMP timeout but still start auction, when `purpose: 'basicAds', enforcePurpose: false,` is in config.

## Test page
[https://playground.cpex.cz/headerbidding](https://playground.cpex.cz/headerbidding)

### Expected results
Auction to run

### Actual results
Auction not running

## Platform details
Prebid.js v5.2.0 (v4 behaves the same)
MacOS, Chrome

## Other information
None

**Comment by gglas** [comment] 2021-07-19 15:31
@bretg will have a look, first read is this is not desired behavior.

**Comment by bretg** [comment] 2021-07-19 19:23
@EskelCz - looked at your test page. Can you please provide instructions for how to reproduce the problem on this test page?

I clicked on the grey buttons in the CMP-looking boxes and wound up with a TCF string with no perms. Auctions were run for 4 bidders.

This seems to be the behavior you're looking for.

I do see a "tcf2Enforcement" event firing, but setting a breakpoint indicates that nothing is actually enforced: no bidders, storage, or analytics blocked.

**Comment by EskelCz** [comment] 2021-07-20 11:12
@bretg The CMP should definitely come back when you clear all cookies and localStorage. Anyway the issue is the auction not running when the CMP is open, so please leave it untouched.

The instructions is therefore just opening the page and looking into the console/network. From our understanding of the prebid configuration, the auction should be running, based on the disabled "basic ads" enforcement.

Just to make it complete, here are screenshots of the relevant logs.
<img width="1438" alt="Screenshot 2021-07-20 at 12 18 40" src="https://user-images.githubusercontent.com/1198558/126314602-6831e457-b415-4a04-ad35-914e7b2d876c.png">
<img width="1438" alt="Screenshot 2021-07-20 at 12 28 31" src="https://user-images.githubusercontent.com/1198558/126314613-486efa82-bd45-4b5f-bc28-7f5ca26ee7f0.png">

**Comment by bretg** [comment] 2021-07-20 21:23
Looked in the code. This timeout logic doesn't even look at the `basicAds` config: 

From modules/consentManagement.js:
```
    if (errMsg) {
      if (allowAuction.value && cmpVersion === 1) {
        utils.logWarn(errMsg + ` 'allowAuctionWithoutConsent' activated.`, extraArgs);
        nextFn.apply(context, args);
      } else {
        utils.logError(errMsg + ' Canceling auction as per consentManagement config.', extraArgs);
        if (typeof hookConfig.bidsBackHandler === 'function') {
          hookConfig.bidsBackHandler();
        } else {
          utils.logError('Error executing bidsBackHandler');
        }
      }
```

Basically, the CMP timeout condition is short-circuiting the parsing of the GDPR config and just invoking the callback handler.

It's somewhat arguable whether an auction is really useful after a 10 second CMP timeout... really?  In the vast majority of the cases, I'd think that publishers who default to in-scope for GDPR are going to be cautious about running auctions without user input.

But if you guys feel this is a valid use case, I suppose it can't hurt to change the timeout path so that it initiates the auction as normal and lets _that_ flow cancel the auction in 95% of the cases.

**Comment by patmmccann** [comment] 2021-07-20 21:49
With the merging of https://github.com/prebid/Prebid.js/pull/6484 ; I think publishers may frequently run an auction on timeout

**Comment by EskelCz** [comment] 2021-07-21 12:24
@bretg Right, that's the issue. The thing is, we don't really want to wait for the consent very long. Our publishers have the timeout set to something like 3 seconds. In our market (Czech Republic) there was a ruling establishing blanked legal basis for basic ads, so we prefer having that instead of nothing (some users completely ignore the banner), for the first page load. Since we cover about 80% of our internet population, this use case is of real significance.

**Comment by gglas** [comment] 2021-11-08 16:57
@EskelCz we're prioritizing this among other bugs, but will be addressing.

**Comment by bretg** [comment] 2021-11-16 20:41
The action to take with this ticket is to update the CMP timeout scenario in modules/consentManagement.js to run the auction rather than immediately invoking the bidsBackHandler.

Depending on the consentManagement config, this may cancel the auction anyhow.

I'd argue this is a bug and not a breaking change so it doesn't need to wait for a major release and doesn't need config to 'turn it on'. Publishers have set up their preferred ConsentManagement approach and the auction should respect that rather than being canceled automatically.

**Comment by EskelCz** [comment] 2021-11-19 14:45
@bretg @gglas Perfect. Should we try to open a PR, or will you handle it internally? We don't have any experience with prebid codebase but we can try :)

**Comment by dgirardi** [comment] 2021-11-19 18:34
@EskelCz I'm picking this up right now, a PR should come somewhat soon.

**Comment by dgirardi** [comment] 2021-11-22 18:44
@jsnellbaker the proposed fix for this is in direct contradiction with this test case:
https://github.com/prebid/Prebid.js/blob/329deb846394252eaef5c7cf52eeeb8d83b07f48/test/spec/modules/consentManagement_spec.js#L696-L716

Why is that there - what's the harm in continuing the auction with no consent data?

**Comment by dgirardi** [comment] 2021-11-22 18:56
@EskelCz if we go ahead with the fix suggested above, and using `enforcePurpose: false` as you describe, explicitly denying consent would have no effect for the purpose of basic ads and storage. Is this what you are expecting? (I believe `allowAuctionWithoutConsent` applied only to the case where no consent data was available - that is, the popup was being ignored, which does not look like the same effect to me).

**Comment by EskelCz** [comment] 2021-11-23 13:09
@dgirardi That is just what worked for us in previous versions. In our market (czech republic) we don't legally need consent for basic ads.
If you feel this calls for a different configuration, that's fine with us. We just need an option to run the auction when the popup is still open.

**Comment by EskelCz** [comment] 2021-11-23 21:35
@dgirardi Thanks for the breakdown, but at least half of our market is using custom SAS based ad-servers, so it still has an impact.

**Comment by dgirardi** [comment] 2021-11-23 22:03
@EskelCz just discussed this offline and yes, we agreed it should be fixed - it's just going to involve a bit more work than we anticipated. This issue is still at the top of my list.

**Comment by dgirardi** [comment] 2021-11-24 22:28
Since now auctions don't start until consent data is resolved through the CMP, modules never saw the case where `consentData.gdprApplies` is `true` but `consentData.consentString` is not defined. This would change if we allow the auction to continue without consent data, and there are several modules that in my estimation would not work correctly. 

This is an attempt at an exhaustive list, but I can't guarantee I haven't missed some.

These modules ignore `gdprApplies` completely:

https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/addefendBidAdapter.js#L17-L26
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/apstreamBidAdapter.js#L288-L293
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/glimpseBidAdapter.js#L138-L153
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/improvedigitalBidAdapter.js#L47-L50

These talk to endpoints that appear to treat a missing consent string as equivalent to "gdpr does not apply":

https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/adnuntiusBidAdapter.js#L68
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/beopBidAdapter.js#L43-L54
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/criteoIdSystem.js#L136-L143

These only consider `gdprApplies` if a consent string is available:

https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/cleanmedianetBidAdapter.js#L90-L104
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/engageyaBidAdapter.js#L131-L133
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/gamoshiBidAdapter.js#L104-L109
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/stroeerCoreBidAdapter.js#L141-L145


These don't appear to consider `gdprApplies` for user syncs if no consent string is avialable:

https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/bliinkBidAdapter.js#L273-L278
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/districtmDMXBidAdapter.js#L202-L208
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/loganBidAdapter.js#L138-L144
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/mathildeadsBidAdapter.js#L186-L192
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/mediasquareBidAdapter.js#L141
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/onetagBidAdapter.js#L350-L355
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/richaudienceBidAdapter.js#L149-L151
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/rubiconBidAdapter.js#L770-L777
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/smilewantedBidAdapter.js#L132-L139
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/tripleliftBidAdapter.js#L88-L91
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/trustxBidAdapter.js#L286-L292
https://github.com/prebid/Prebid.js/blob/e41bbedc28c7cd16da0d0166d900b1dab19191d0/modules/videoreachBidAdapter.js#L81-L87

**Comment by EskelCz** [comment] 2021-11-26 12:40
@dgirardi Ok that's not easy, I understand. Are those adapters managed by the SSPs or by the Prebid team?

**Comment by dgirardi** [comment] 2021-11-29 17:35
@EskelCz I believe for at least some of them we need to involve the SSPs - but I'll try to submit something that will work if you are not using those particular ones. Btw, I'm using this issue to keep track, I don't expect that list to be particularly interesting to you :)

**Comment by dgirardi** [comment] 2021-11-29 17:56
@EskelCz can you extract out Prebid's configuration from the test page you provided? (it seems to be all zipped up and minified with the rest of the site). It'd be helpful to have something where I can just swap out `<script src="some-prebid-version.js" />` with my own so I can test whether my changes would work for your use case.

**Comment by dgirardi** [comment] 2021-11-29 18:44
@EskelCz alternatively, you can try to see if https://github.com/prebid/Prebid.js/pull/7769 works for you. I don't know if it's a good idea to merge that in as-is, but it should be enough for you to test.

**Comment by dgirardi** [comment] 2021-12-01 17:04
@EskelCz with that test page, both rubicon and and pubmatic return no bid (I believe because gdpr does not allow them: rubicon says "internal error", pubmatic says "204 no content"). I don't think they would work even if you used an old prebid version and `allowAuctionWithoutConsent` - I'm curious about which bidders worked for you with that. Regardless of what prebid does, they also need to be generous with how they interpret GDPR on their end for bids to happen.

Also, `sas-tracker-2.3`, which you use in the first test page you provided, interacts with the CMP on its own like GPT does - look for `getConsentString` in the source. It's likely that it would also not behave correctly when the popup is left open.

**Comment by EskelCz** [comment] 2021-12-02 12:09
@dgirardi Interesting, we're pretty sure it worked not too long ago. We'll turn it around with those SSPs, I'll let you know.

**Comment by bretg** [comment] 2021-12-07 17:41
There may be some bidders willing to downgrade the request to be contextual-only in the case of gdpr-applies:true with empty consent string. Others are going to reject the request outright. Depends on their legal teams.

**Comment by dgirardi** [comment] 2021-12-14 19:02
closing this with the merge of https://github.com/prebid/Prebid.js/pull/7769

**Comment by EskelCz** [comment] 2022-05-23 10:43
> There may be some bidders willing to downgrade the request to be contextual-only in the case of gdpr-applies:true with empty consent string. Others are going to reject the request outright. Depends on their legal teams.

Sorry to return to this, it took us some time to put this into production. We noticed that in the case of the auction ran without consent, Prebid is sending `tcString: undefined`.

From your comment I assumed that by empty you mean a valid tcString without purposes and consent (the string that CMP gives you by default). So I'd like to make sure we mean the same thing by an "empty string", and whether I should reopen this thread for this sub-issue, or make a new one.

**Comment by EskelCz** [comment] 2022-05-23 16:20
@dgirardi I don't think that's needed. In case of TCF v2 specification, the CMP has to respond to `__tcfapi('getTCData', 2, function(data) { console.log(data)})` at any time with the current consent state. In case of the open banner it is functionally "empty", but valid (from the perspective of the SSP).
Like this one:
`CPZRIQAPZRIQAAHABBENCQCgAAAAAEPAAATIAAANTgTAAVAAuABwAEAAMgAaAA5gCIAIoATAAngBVAC4AGIAMwAfgBCQCIAIkARwApQBYgDLAGbAO4A7wB-gEIAIsAXUAwIBrADqAHyASCAm0BagC8wGSANKAamAIGgAwABBGIRABgACCMQqADAAEEYhkAGAAIIxAAAA.YAAACHgAAAAA`
Decoder: [](https://iabtcf.com/#/decode)

**Comment by EskelCz** [comment] 2022-05-23 16:24
![1927bf11-18b4-4db1-bb9b-fc1cade678b9](https://user-images.githubusercontent.com/1198558/169864230-cf083242-4a52-439b-ac9c-19a4ec18a91d.png)

**Comment by dgirardi** [comment] 2022-05-23 16:51
I stand corrected then, and I agree Prebid should attempt to retrieve consent data on timeout. Although it appears that not all CMPs work that way:

![NoTCString](https://user-images.githubusercontent.com/10151381/169869455-08e5120d-3cba-4711-9669-dac6240106ab.png)

**Comment by EskelCz** [comment] 2022-05-23 17:51
@dgirardi Seems like the docs are not clear about it. But either way passing the CMP value should better than undefined. Thanks

**Comment by EskelCz** [comment] 2022-06-01 14:44
For the sake of completeness my colleague read up on issue, these are his notes:

1. According to TCF policies (https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/):
“…a Vendor must forward the Signal communicated by a CMP or received from a Vendor who forwarded a Signal originating from a CMP, in accordance with the Specifications and Policies to its Vendor-partners present on its services.”
Prebid is not exactly a vendor, nevertheless, this is one of the main rules of the TCF - if you have the TC string, you should pass it down the chain, so other vendors can act accordingly.

2. “A Vendor must respect Signals communicated by a CMP …. A Vendor must respect Signals on an individual basis in real-time and must not rely on a stored version of a previously received Signal …. If a Vendor is unable to read or process the contents of a received Signal, the Vendor must assume that it does not have permission to store and/or access information on a device, or to process personal data for any Purpose.”

In our case, if no choice has been made, that means that user has not given explicit consent but also has not objected to Legitimate interest. If we pass that information, some bidders can at least try to sell the impression without personal data. If we pass nothing, they have to assume consent was declined and drop the request.

Also, we have been approached by one of our bidders (Xandr) - they don’t want us to request their endpoint if we can’t provide the consent string. They consider that non-compliant. This relates to point 1 above - the information about the user choice (or the absence of choice) should be clear and transparent and if you have it, you should pass it further.

**Closed** 2022-06-13 18:25 UTC
Labels: bug
