### ISSUE TITLE
Possible issue with buffer on bid cache TTL

### ISSUE THREAD

**Issue by nlavallee-sortable** [prebid/Prebid.js#6216] opened 2021-01-25 14:54 UTC
## Type of issue
Bug

## Description
Unless I'm misunderstanding the purpose of the `TTL_BUFFER` constant, it's being applied incorrectly.

The calculation in [targeting.js](https://github.com/prebid/Prebid.js/blob/680541838b87652fbe6e3cc2beb2dd25642c394a/src/targeting.js#L23) adds the bid's TTL to the response timestamp but then adds a 1 second buffer. I assume this is to prevent a bid from being rendered after it has expired by ensuring a bid is not used within its final second of life. However, what this actually does is extend the bid's life by an extra second, allowing some bids to be used up to a second after expiration.

The `TTL_BUFFER` should either be subtracted from the expected time (left side), or added to the current time (right side).

For a quick example, let's say you receive a bid with a timestamp of midnight, and a TTL of 60 seconds. The bid should therefore be used no later than 12:01:00. A buffer of one second can be used to play it safe by saying the bid shouldn't be used after 12:00:59. The current calculation, however, adds the buffer to the expiry time instead of subtracting it, so it computes that the bid is valid up to 12:01:01.

**Comment by bretg** [comment] 2021-01-26 20:35
@nlavallee-sortable - please explain why you care about bids lasting one second longer than specified.

I don't know the history behind the addition of the TTL_BUFFER, but would assume there was a good reason at one point. The javascript environment is subject to inaccuracies in timing, so adding a small buffer doesn't seem like a bad idea to me.

So at this point I'm leaning towards letting this one go, but open to an explanation for why 1 second is a big problem for you.

Does anyone recall the original need for  TTL_BUFFER?

**Comment by bretg** [comment] 2021-01-26 20:36
And for the record, I don't view the calculation as "faulty", so changing the title here. The question here is really "why is there a TTL buffer at all?"

**Comment by nlavallee-sortable** [comment] 2021-01-26 20:56
To be honest, I can only assume why it was there. I tried looking through the history, but the only mention was during [the PR](https://github.com/prebid/Prebid.js/pull/2328) where it was introduced, and there was never a mention of *why*.

According to [this documentation](https://docs.prebid.org/dev-docs/bidders.html) (search for TTL):

> If an invalid bid wins, and its associated ad is rendered, it will not count towards total impressions on IX’s side.

This is only for one bidder and I'm making yet more assumptions, but I assume this is true for other bidders, and I assume that if any bid is chosen after their expiration, then you will get problems either during rendering or during reporting.

> The javascript environment is subject to inaccuracies in timing, so adding a small buffer doesn't seem like a bad idea to me.

That's why I think that was their original reasoning - to allow a bit of a buffer due to timing issues, reduce the expiration by a second to prevent its use in the final second of its life, to ensure an expired bid doesn't get accidentally rendered. The reason I call the calculation faulty is because it does the opposite of this, by extending the bid's lifetime by an extra second rather than reducing it.

**Comment by bretg** [comment] 2021-01-26 21:28
The TTL_BUFFER is almost 3 years old, from https://github.com/prebid/Prebid.js/pull/2328

Ok, I see where you're going with this. 

If bidders have set a hard deadline and are going to ignore cached bids precisely at X time, then I agree with you that the buffer should be subtracted. 

But I doubt bidders are actually that hard-nosed. They probably don't have record of the precise second when the bid was made, and I doubt they'll cut off a render that's one second over the limit. But I could be wrong. Are you seeing some numbers that indicate a problem?

Though it was a long time ago, perhaps @jaiminpanchal27 or @mkendall07 might remember what drove the inclusion of TTL_BUFFER?

**Comment by mkendall07** [comment] 2021-01-26 22:45
Hey @nlavallee-sortable. I just looked at this and I think the logic is working as intended? 
Let's walk through a quick example - lets assume a 120 second bid.ttl. 
```
Let's say we get a bid with this timestamp:
1611700197146

After 119,100ms - the bid is technically *not* expired (119,100 < 120,000), however with our buffer we want this to be expired based on 1 second buffer. 

The current logic is: (bid.responseTimestamp + bid.ttl * 1000 + TTL_BUFFER) > timestamp())
so...
1611700197146 + 120 (seconds ttl) * 1000 + 1000 = 1611700318146

1611700318146 > 1611700316246 = true (bid expired) 
```
Let me know if I did any math wrong though.

**Comment by nlavallee-sortable** [comment] 2021-01-26 22:57
You did the math completely right, but `true` here means `not expired`.

`1611700318146 > 1611700316246 = true (bid expired)`
In this example, 1900ms remain until this no longer returns true (I subtracted the right side from the left side). This means the bid will be "not expired" until 121,000.

**Comment by nlavallee-sortable** [comment] 2021-01-26 22:59
> Are you seeing some numbers that indicate a problem?

No data unfortunately, this is all in theory land. I happened to look at the calculation to see what it was doing and I spotted it.

**Comment by mkendall07** [comment] 2021-01-27 02:42
> You did the math completely right, but `true` here means `not expired`.
Oh I was looking at the PR not master, looks like it was switched to `bidNotExpired`. Ok yeah I see you point, feel free to submit a PR for a correction.

**Comment by ChrisHuie** [comment] 2021-02-18 12:28
#6300 closing out this issue

**Closed by ChrisHuie** 2021-02-18 12:28 UTC
