### ISSUE TITLE
Aliases AppnexusAstBidder

### ISSUE THREAD

**Issue by Deimos01** [prebid/Prebid.js#1682] opened 2017-10-11 21:06 UTC
## Type of issue
Bug/Question

## Description
I'm trying to use Brealtime with the AppnexusAst bidder. Is it still possible ?

## Steps to reproduce
I'm trying to implement aliases with the new specs : http://prebid.org/dev-docs/bidder-adapter-1.html
Just added this line on the AppnexusAstBidAdapter.js
```
export const spec = {
  code: BIDDER_CODE,
  aliases :['brealtime'],
  supportedMediaTypes: [VIDEO, NATIVE],

```
## Test page
https://www.themoneytizer.com/demo/geoprebid?pbjs_debug=true

### Actual results
![image](https://user-images.githubusercontent.com/5635647/31466524-81ec8024-aea5-11e7-8222-1cd2bfb9e043.png)

## Platform details
Prebid version 0.30.1

Thank you !

**Comment by jaiminpanchal27** [comment] 2017-10-16 16:38
Yes it is possible. Whenever something is wrong with response bidderFactory handles that and logs a generic error message as you see that above.
 
You can see the error response in network tab.

For AppnexusAst, I have created #1697 to log actual error message received from endpoint to find root cause easily.

**Comment by jaiminpanchal27** [comment] 2017-10-17 14:19
#1697 is merged so closing this.

**Closed by jaiminpanchal27** 2017-10-17 14:19 UTC

**Comment by Deimos01** [comment] 2017-10-17 14:25
Hello @jaiminpanchal27 ,

So i have to wait the next Prebid release to use Brealtime with the AppnexusAst bidder ?

Thank you very much.

**Comment by jaiminpanchal27** [comment] 2017-10-17 14:32
@Deimos01 Its not a blocker for you. This is the response for brealTime Request `{"error":"Could not find valid member in request"}` on your test page. I think you need to update your config.

In #1697 i am logging that error message in console to help debug faster.

Also we are doing a release today so you will see the error message received in response.

**Comment by Deimos01** [comment] 2017-10-17 14:51
Thank you very much @jaiminpanchal27 !
