### ISSUE TITLE
hb_uuid is set to undefined when running video ads

### ISSUE THREAD

**Issue by amanjain** [prebid/Prebid.js#1857] opened 2017-11-21 08:16 UTC
We had setup video ads using the steps given in:
http://prebid.org/dev-docs/examples/jw-selfhost-example.html and
http://prebid.org/dev-docs/show-video-with-a-dfp-video-tag.html and 
http://prebid.org/examples/video/jwPlayerPrebid.html

hb_uuid of cust_params is set as undefined

<img width="439" alt="screen shot 2017-11-21 at 11 09 59 am" src="https://user-images.githubusercontent.com/435017/33061478-48616116-cec2-11e7-8a80-0af34b2d092d.png">

and hence we are getting 400 error.  Any insights?

**Comment by GeneGenie** [comment] 2018-01-09 16:58
Any reactions to this? I'm having the same issue

**Comment by dbemiller** [comment] 2018-01-09 17:03
did you set the config to use the cache?

```
pbjs.setConfig({
  /* Or whatever your preferred video cache URL is */
  cache: {
    url: 'https://prebid.adnxs.com/pbc/v1/cache'
  }
});
```

If you missed that step, there would be no UUID used to fetch the VAST.

**Comment by mkendall07** [comment] 2018-01-09 17:05
yeah above ^ is most likely the cause. Sorry for the confusion, I don't think we documented this change very well. We should probably also warn in this case in the console.

**Comment by GeneGenie** [comment] 2018-01-09 17:08
@mkendall07 I would add it near buildVideoUrl and setConfig sections.

**Comment by matthewlane** [comment] 2018-02-08 19:47
Closing with #1663 and https://github.com/prebid/prebid.github.io/pull/462 merged

**Closed by matthewlane** 2018-02-08 19:47 UTC
