### ISSUE TITLE
Prebid 12 - pbjs.requestBids - returns all ads, not just ads in paths array.

### ISSUE THREAD

**Issue by internetchris** [prebid/Prebid.js#590] opened 2016-08-31 19:36 UTC
Hi Group,

I just upgraded to version 12 today and noticed that when I do a request bids on an ad I'm refreshing, it gets bids for all my ads, not just the ad specified in my paths array. Thoughts?

```
pbjs.que.push(_.bind(function() {
      pbjs.requestBids({
        timeout: PREBID_TIMEOUT,
        adUnitCodes: paths,
        bidsBackHandler: _.bind(function(bidResponses) {
           // bidResponses comes back with all ads, not just the ads in my paths array
        }, this)
      });
    }, this));

```

In my console I set a breakpoint and put a watch on the `paths` and the `bidResponses`

<img width="702" alt="prebid issue" src="https://cloud.githubusercontent.com/assets/45402/18143467/636313f4-6f7f-11e6-9a62-18a7d9d1f9e1.png">

We are currently using version 8 due to some compatibility problems with IE, but with that version it only returns the skyscraper in the bidResponse since that's all I passed in our paths array.

**Comment by internetchris** [comment] 2016-09-06 16:42
Checking back on this. Anyone here have a moment to confirm my findings?

**Comment by mkendall07** [comment] 2016-09-06 16:42
@internetchris 
I'll take a look at this

**Comment by mkendall07** [comment] 2016-09-06 20:48
@internetchris 
Yes it looks like this is an issue. I'm not sure if it was working properly before or not, but we'll fix it as part of some internal changes we are making to our auction instances.

**Comment by aforwark** [comment] 2016-10-20 17:46
Do we think this will be resolved by the release of Prebid 0.14.0?

**Comment by protonate** [comment] 2016-10-24 23:27
The expected behavior currently is you will see the bid data for the most recent auction a placement participated in. For example, for 5 placements on a page, a bid request is made for all five placements, then for four of the five and then for 3. `pbjs.getBidResponses` will return:

| placement | auction |
| --- | --- |
| 1 |  1 |
| 2 |  2 |
| 3 |  3 |
| 4 |  3 |
| 5 |  3 |

You can filter these results to report on just the most recent auction. Closing as answered, please reopen with any new info.

**Comment by mkendall07** [comment] 2016-10-25 01:09
@protonate 
This is for the bidsBackHandler param, not `pbjs.getBidResponses`. I don't think that has been resolved?

**Comment by internetchris** [comment] 2016-10-25 03:21
Indeed - thanks for re-opening @mkendall07..... we are really hopeful to see this fixed in v14 - what's the likelihood?

**Comment by protonate** [comment] 2016-10-27 22:53
@internetchris #750 should address the issue. It is expected to be released with Prebid 0.14.0.

**Comment by internetchris** [comment] 2016-11-02 18:54
I've been following the progress of this. If we wanted to use this once it's been merged, it may be reasonable if there hasn't been a bunch of other changes merged since releasing 0.14.0. I will keep a close eye on it.

**Comment by protonate** [comment] 2016-11-06 06:40
@internetchris @aforwark #750 is now updated and should fix the issues you've reported. If you are able to test the PR branch for your use case let us know.

**Comment by internetchris** [comment] 2016-11-06 14:38
I will give this a test tomorrow. Thanks!

**Closed** 2016-11-11 14:38 UTC
Labels: bug

**Comment by aforwark** [comment] 2016-11-15 22:21
@protonate I'm late to the party but just confirming this is working great now, thank you!

**Comment by protonate** [comment] 2016-11-15 23:36
@aforwark glad to hear it, thanks for the update.

**Comment by internetchris** [comment] 2016-11-18 20:17
@protonate  - I may be missing something but if I simply pass a single path 

```
  pbjs.requestBids({
        timeout: PREBID_TIMEOUT,
        adUnitCodes: ['/mypath'],
        bidsBackHandler: _.bind(function(bidResponses) {
          console.log('bidResponses', bidResponses);
```

I'm don't get any bidResponses. Is there something new I must do? I just build v0.15.0

**Comment by protonate** [comment] 2016-11-18 20:34
You do have an adUnit defined for '/mypath'?

**Comment by internetchris** [comment] 2016-11-18 20:56
yep: 
![screen shot on 2016-11-18 at 13-54-02](https://cloud.githubusercontent.com/assets/45402/20446403/9dd81836-ad96-11e6-844b-0c4dac0d8882.png)

Code snippet: 

```
    console.log('pbjs.adUnits', pbjs.adUnits);
    console.log('paths', paths);

    pbjs.que.push(_.bind(function() {
      pbjs.requestBids({
        timeout: PREBID_TIMEOUT,
        adUnitCodes: paths,
        bidsBackHandler: _.bind(function(bidResponses) {
          console.log('bidResponses', bidResponses);
```

**Comment by internetchris** [comment] 2016-11-18 21:01
Here's a little more output with the pbjs_debug...

![sample-prebid](https://cloud.githubusercontent.com/assets/45402/20446549/74549b6e-ad97-11e6-803f-7f9a123605c1.png)

**Comment by internetchris** [comment] 2016-11-18 22:09
cc/ @mkendall07  - looping you into this conversation too, I know you handled reproducing my original issue. I'm hoping I'm just being dense about this.

**Comment by protonate** [comment] 2016-11-18 22:40
Seems like the callback is invoked before the bids have returned, either due to timeout or an issue with bid counts (which we thought had been resolved). Does lengthening the timeout change anything?

**Comment by internetchris** [comment] 2016-11-18 22:46
Extending the timeout didn't have any affect. I tried 5000ms and then for the heck of it 15000ms, the bidResponse/lack of seems immediate.

**Comment by protonate** [comment] 2016-11-18 22:52
After running the auction what are the contents of `pbjs._bidsRequested` and `pbjs._bidsReceived`?

**Comment by internetchris** [comment] 2016-11-19 00:52
So on page load we load all our ads, the `bidsRequested` and `bidsRecieved` are full and look legit. If I run our refresh and request bids for any one of these units after page load, lets say the Leaderboard as an example, then I'm simply passing the path of that leaderboard ad to the `requestBids` method following the `requestBids` action I checked the `bidsRequested` and `bidsRecieved` against the original request and receive and they are identical. It doesn't look like those arrays changed at all. I would be happy to provide a staging url in a private message if you're interested.

**Comment by protonate** [comment] 2016-11-19 01:22
That would be great, please email me, address is in my profile.
