### ISSUE TITLE
Identifying auction winner through Analytics Provider

### ISSUE THREAD

**Issue by fafnirbcrow** [prebid/Prebid.js#1736] opened 2017-10-20 16:24 UTC
## Type of issue
Question

## Description
We are trying to implement a custom analytics adapter, and per the documentation, we are trying to hook in to the BID_WON event to determine the auction winner. However we are seeing that the BID_WON event is not always emitted. 

Based on observations of our pages, and reading through the issues, I believe that DFP/googletag are not returning BID_WON events when they take the ad slot. This is based on our observations of ads all being filled, a event being emitted for auctionEnded, but not for renderAd or BID_WON

This seems similar to issue #1642 when the user mentions that he does not always see a bid won.

From issued #1289 where matthewlane responds that googletag.pubads().refresh(); 'would refresh all slots, but it should invoke renderAd' I would expect that the googletag would still emit the event with information showing that DFP is taking the slot. 

## Steps to reproduce
1. Run prebid.js on page in debug mode
2. Observe events emitted in console
3. Auctions which end do not always seem to then call renderAd/BID_WON even when a ad is visibly shown

### Expected results
Every auction should emit a renderAd/BID_WON event

### Actual results
These seem intermittent at best

## Platform details
prebid .30.1, .25.0 at least

**Comment by mkendall07** [comment] 2017-10-20 16:48
This is expected behavior. Since we have no knowledge of when a prebid creative is not selected, we cannot emit an event telling you no prebid creative won. Make sense.

**Comment by mkendall07** [comment] 2017-10-20 17:06
The comment in #1289 talks about `renderAd` being called after refresh but the assumption is only if a prebid line item wins. 

In the case where prebid line item doesn't win, `renderAd` is not called. So again really isn't a way for us to emit an event, other than waiting some period of time and guessing that we did not win. That's not a great solution though, so I don't plan on building that into the library.

**Comment by fafnirbcrow** [comment] 2017-10-20 17:18
I would agree that guessing is a terrible plan. I guess what is missing then seems to be a gap then in the documentation of how from a AnalyticsAdapter direction we would be able to track those impressions. 

My best guess would be to collect all AuctionEnd events, and then subtract all bid_wons as a way to estimate the total of DFP, but I don't know if there would be something better from a library perspective of tracking that data.

**Comment by mkendall07** [comment] 2017-10-20 21:17
@fafnirbcrow I don't understand what you are trying to track. You have bids requested that go out. If you don't receive a subsequent request updating the bid to some other status you can assume it did not win.

**Comment by dmitriyshashkin** [comment] 2017-11-15 17:49
Not sure if it helps, also not sure if it is allowed to do within the analytics adapter, but GPT has events and you can add a listener to detect the situations when not HB advertiser has won the auction: https://developers.google.com/doubleclick-gpt/reference#googletageventsslotrenderendedevent

It provides you with the advertiser id, theoretically, you can ask publishers to provide you with the list of the advertiser ids that correspond to the HB bidders, so once you get slot render ended event with the advertiser id not in this list, you can count it as a not-HB bid Won.

Then again it's not clear whether there is any point in such functionality as DFP doesn't provide the CPM and mixing HB and not-HB stats seems a bit odd.

**Comment by mkendall07** [comment] 2017-11-29 21:31
@dmitriyshashkin 
Very interesting idea. Not super important for us but willing to explore the possibility of adding this as an API if someone wants to do the work. Going to close this out for now though.

**Closed by mkendall07** 2017-11-29 21:31 UTC
