### ISSUE TITLE
Doceree AdManager : "error":"Prebid file not built properly" 

### ISSUE THREAD

**Issue by Doceree-techStack** [prebid/Prebid.js#12313] opened 2024-10-10 12:45 UTC
## Type of issue
Bug

## Description
Unable to download the prebidJS file for adapter: Doceree AdManager. Throwing error : "{"error":"Prebid file not built properly","requestId":"d1787589-24fe-4574-b299-a777dbb93bea"}".

## Steps to reproduce
1. Visit page: "https://docs.prebid.org/download.html".
2. Select "Doceree AdManager".
3. Click on get Prebid.js
4. Upon opening file showing error message

### Expected results
Publisher should be able to download the prebid.js file without any issues
## Platform details
Checked for 9.14.0 and 9.15.0, please address for all versions

**Comment by dgirardi** [comment] 2024-10-10 14:08
This issue was fixed in https://github.com/prebid/prebid.github.io/pull/5260 and re-introduced in https://github.com/prebid/prebid.github.io/pull/5575

Also related: https://github.com/prebid/prebid.github.io/issues/5636

**Comment by ChrisHuie** [comment] 2024-10-10 14:20
@Doceree-techStack download page now seems to be working as intended for your adapter. Please confirm.

**Comment by Doceree-techStack** [comment] 2024-10-11 07:09
@ChrisHuie Everything's working fine now! 
As highlighted by @dgirardi, this is 2nd occurrence of the same issue. Please ensure that the adapter code is not modified by the prebid support team without our knowledge, as such issues have high impact on our business continuity.

**Comment by patmmccann** [comment] 2024-10-11 18:12
@Doceree-techStack : @pm-azhar-mulla at Pubmatic contributed this change.

**Closed** 2024-10-13 20:20 UTC
