### ISSUE TITLE
Native: image min-width/min-height attributes

### ISSUE THREAD

**Issue by coreyb-cbs** [prebid/Prebid.js#6654] opened 2021-04-26 16:29 UTC
## Description
Provide the ability to include `min_width` and `min_height` on the _image_ asset without requiring `ratio_width` and `ratio_height`. OpenRTB native spec differs from Prebid native spec in regards to _min-width_ and _min-height_ attributes for image assets. ORTB includes _image.wmin_ and _image.hmin_. Prebid has attributes that represent the same thing, but they're nested inside the _aspect_ratios_ attribute and _aspect_ratios.ratio_width_ and _aspect_ratios.ratio_height_ are required if the _aspect_ratios_ option is included. Both publishers and bidders would like to have the ability to include _min-width_ and _min-height_ attributes on _image_ assets without being forced to include an aspect ratio. Including an aspect ratio reduces the potential bid pool. GAM native styles, especially of Fluid size, can responsively handle images of various dimensions and aspect ratios.

OpenRTB spec (_image_ asset is on page 15):
https://www.iab.com/wp-content/uploads/2018/03/OpenRTB-Native-Ads-Specification-Final-1.2.pdf

## Proposal
The _image_ asset could look like any of the following (all attrs optional):
```
image: {
     required: true,
     sizes: [300, 200]
}
```
```
image: {
     required: true,
     min_sizes: [300, 200]
}
```
```
image: {
     required: true,
     min_sizes: [300, 200],
     aspect_ratios: [3, 2]
}
```

## Note
The same could be applied to the _icon_ asset.

**Comment by coreyb-cbs** [comment] 2021-04-28 15:10
Or a simpler alternate proposal which doesn't require an attribute re-factor is to allow the use of `aspect_ratios.min_width` and `aspect_ratios.min_height` without requiring `aspect_ratios.ratio_width` and `aspect_ratios.ratio_height`. It doesn't feel proper that they're still nested inside `aspect_ratios`, but it's a less-disruptive modification.

So updating the following line:
https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js#L500

to this:
`if (params.aspect_ratios.ratio_width && params.aspect_ratios.ratio_height) {`

And therefore update the error message in this line:
https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js#L498

to this:
`throw 'invalid img sizes (must provide sizes or min_height & min_width)';`

**Comment by ChrisHuie** [comment] 2021-08-02 13:57
@coreyb-cbs is this still an issue? I know we made a few different native image prs in recent releases and think one solved this.

**Comment by coreyb-cbs** [comment] 2021-08-03 17:00
@ChrisHuie I'll review the current Prebid S2S adapter to see if my original concerns have been resolved. Thanks!

**Comment by coreyb-cbs** [comment] 2021-08-16 15:22
@ChrisHuie My comment from April 28 is still relevant:

> Was testing the case to include aspect_ratios.min_width and aspect_ratios.min_height and not include aspect_ratios.ratio_width and aspect_ratios.ratio_height and it seems the only drawback is that asset.ext is sent as [undefined,undefined]. Ideally asset.ext wouldn't have a value if aspect_ratios.ratio_width and aspect_ratios.ratio_height were not included in the params.

[This conditional](https://github.com/prebid/Prebid.js/blob/master/modules/prebidServerBidAdapter/index.js#L542) should be more specific since it's possible to include `aspect_ratios.min_width` and `aspect_ratios.min_height` without including `aspect_ratios.ratio_width` and `aspect_ratios.ratio_height` and the subsequent code only deals with `ratio_width` and `ratio_height` when setting the `ext` object.

So at the moment it's:
`if (Array.isArray(params.aspect_ratios)) {` 
and I believe it should be: 
`if (params.aspect_ratios.ratio_width && params.aspect_ratios.ratio_height) {`

We are including `min_width` and `min_height` in our requests but we are not including `ratio_width` and `ratio_height` so the `ext` object gets set with undefined values.

**Comment by coreyb-cbs** [comment] 2021-08-19 16:15
@ChrisHuie please reopen ^^^^^

**Comment by ChrisHuie** [comment] 2021-08-30 14:05
@coreyb-cbs I will work on a fix here this week

**Comment by bretg** [comment] 2021-11-16 22:01
@coreyb-cbs - no one's picked this up because we don't have someone who understands native well enough to see the impacts here end-to-end. So maybe you can help us define what needs to change specifically with respect to the pbsBidAdapter and how PBS needs to accept it? I personally want to avoid constantly tuning PBJS-specific native stuff when it should just be ORTB2.

Also it needs to be noted that PBS is a stickler about proper ORTB2.5. But it doesn't know anything about the Native extensions. If an incoming request doesn't conform, it will be rejected.

Question: What does the native ORTB actually look like? The examples in the native 1.2 doc are partial. My best guess from the docs and from https://github.com/prebid/Prebid.js/blob/c9823f68b26e10f18609177237efab251768046b/modules/prebidServerBidAdapter/index.js#L639 is that imp.native.request is supposed to be a string that contains a JSON object. With quotes escaped. Like this:

```
imp.native.request: "{\"ver\":\"1.2\", \"context\":2, \"contextsubtype\":20, \"plcmttype\":11, \"plcmtcnt\":1, \"aurlsupport\":0, \"assets\": {...}, ... }"
```

If this is correct, I would throw out a fairly dramatic suggestion: how about we begin to sidestep the non-ORTB2 history of PBJS and just throw this right in the mediaTypes.native object. e.g.

```
pbjs.addAdUnits({
    code: slot.code,
    mediaTypes: {
        native: {
            ortb2: STRING-ENCODED-ORTB2NATIVE-FIELD
        }
     }
});
```
Or if that's too unfriendly, perhaps
```
pbjs.addAdUnits({
    code: slot.code,
    mediaTypes: {
        native: {
            ortb2: {
               ver: 1.2,
               ... ETC ... nicely formatted Native ORTB1.2 fields defined right in the AdUnit ...
            }
        }
     }
});
```

On the plus site, native bid adapters (and the pbsBidAdapter) simply need to copy mediaTypes.native.ortb2 into imp.native.request. Then I never again have to think about native and Prebid's annoying non-standard implementation. Life is good.

But there's probably something I'm missing here. Like on the rendering side. It's been so long I've forgotten the details of how the native templates pass data from the bid responses to the in-page renderer. Still, I suspect that's something we can figure out -- like, have the code first check AdUnit.mediaTypes.native.ASSETNAME and if that doesn't exist, check AdUnit.mediaTypes.native.ortb2.assets.ASSETNAME ?

**Comment by dgirardi** [comment] 2021-11-16 22:31
@bretg I believe the issue is translating PBJS AdUnits that define a native image or icon media type into ORTB2 Image objects. Even if they could be passed directly as ortb2 objects, it's probably not right to ignore the adunit definition.

To me it looks like they don't match that well: PBJS native images can have multiple sizes and/or aspect ratios (at least according to the public documentation), while ORTB2 Image has only one size and optional min_height/min_width (which in PBJS land are part of the aspect ratio). The current prebid server adapter will expect there to be only one size defined, and will ignore all aspect ratios except the first.

**Comment by bretg** [comment] 2021-11-19 21:01
> Even if they could be passed directly as ortb2 objects, it's probably not right to ignore the adunit definition.

I'm proposing that we add another "advanced" way of defining the adunit. One that's not proprietary. Publishers that want to use ORTB Native features not supported by Prebid's proprietary interface can instead choose to use the ortb2 version.

The benefit is that we stop digging ourselves a proprietary hole.

The drawbacks are:
- bid adapters would need to change
- we probably need to tweak the render logic

**Comment by ChrisHuie** [comment] 2021-12-02 18:09
Closing with merge of #7722

**Closed by ChrisHuie** 2021-12-02 18:09 UTC
Labels: bug

**Comment by coreyb-cbs** [comment] 2021-12-02 18:18
Thanks @dgirardi and @ChrisHuie !
