### ISSUE TITLE
getSlots() is not defined for a small number of users

### ISSUE THREAD

**Issue by eyedar** [prebid/Prebid.js#340] opened 2016-04-30 05:59 UTC
I'm investigating a big impression discrepancy between my site and a header bidding partner. I have enough evidence that something is wrong on our side, so I've gone into prebid.js and implemented more logging. More specifically, I wrote a server-side logger that receives messages from the client-side through utils.logError() and writes the messages out to our web logs. This allows me to see errors generated by prebid.js on the client side out in the wild.

Our site does about 7M ad requests per day through prebid. Most of the time it works swimmingly without errors. However, we are seeing a few thousand errors per day from this:

```
if (!window.googletag || !utils.isFn(window.googletag.pubads) || !utils.isFn(window.googletag.pubads().getSlots)) {
    utils.logError('window.googletag is not defined on the page');
    return;
}
```

I decided to break this up into 3 if statements with different error messages so I could potentially pinpoint which of these was failing most. So I rewrote it like this and deployed to production:

```
  if (!window.googletag) {
    utils.logError('window.googletag is really not defined on the page');
    return;
  }
  if (!utils.isFn(window.googletag.pubads)) {
    utils.logError('window.googletag.pubads is not a function');
    return;
  }
  if (!utils.isFn(window.googletag.pubads().getSlots)) {
    utils.logError('window.googletag.pubads().getSlots is not a function');
    return;
  }
```

The winner was "window.googletag.pubads().getSlots is not a function." Any idea why out of millions of requests, several thousand fail because there is no getSlots() in pubads (especially when clearly there is for all other requests)?

Looking at the GPT [documentation](https://developers.google.com/doubleclick-gpt/reference#googletagpubadsservice) for pubads, I don't see a getSlots() method even defined, so I don't really understand how this ever works. But since it does work most of the time, I assume it does exist. But it's curious to me that it's missing in the documentation.

Thanks,

Ali

**Comment by mkendall07** [comment] 2016-05-02 17:23
@eyedar 

Thank you for the detailed analysis. Without knowing the specifics of the GPT implementation, I can only speculate that some pieces of the GPT code are not initialized by the timeout triggers. When are you loading GPT (library code) and when is `pbjs.setTargetingForAdUnitsGPTAsync` called? Have you looked at the new loading pattern specified here ? https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_example_gpt.html

**Comment by eyedar** [comment] 2016-05-02 20:49
I have not tried the new loading pattern yet, but I will do so today -- thanks for your suggestion. I'm using the older pattern, where the GPT library code is loaded in the `initAdserver()` callback. I just spent a couple hours walking through all the JS to try to find a condition where `pbjs.setTargetingForAdUnitsGPTAsync()` could be called before `initAdserver()` was called but I couldn't find one. This new loading pattern would ensure that it is loaded 100% of the time. So if timing is the issue, then this error should go away immediately.

I will report back when I have some data. The data I currently have is that this `window.googletag.pubads().getSlots is not a function` appeared about 2500 times on both Saturday and Sunday, and today we're seeing about 150 times per hour.

**Comment by eyedar** [comment] 2016-05-02 21:57
If the first 30 minutes in production is any indication, using the new loading pattern unfortunately did _not_ make a difference. We're still seeing `window.googletag.pubads().getSlots is not a function` at the same rate. 

In fact, now we're getting a surge of totally new kind of error:
`Error processing command :null is not an object (evaluating 'localStorage.dmConsole')`

We get quite a few of these `Error processing command` messages with different descriptions. Clearly something somewhere is putting bogus instructions into the pbjs queue. Should I open up a new issue for these or just ignore?

**Comment by mkendall07** [comment] 2016-05-03 12:40
@eyedar any new insights after using the new pattern? The new error you referenced `localStorage.dmConsole` is not part of prebid.js, that would be some code that you added to the page most likely that got executed inside our queue. Please check your code first and if you can't figure it out open a new issue with your code example so we can replicate.

**Comment by eyedar** [comment] 2016-05-03 15:03
@mkendall07 no new insights; the same issue continues.

Regarding, the `localStorage.dmConsole` message, it is actually not my code. It is coming from an exception being thrown in `pbjs.que.push()`. The `utils.logError()` call on line 62 of prebid.js is generating the message (along with several others).

**Comment by eyedar** [comment] 2016-05-03 19:05
Nix the `localStorage.dmConsole` issue. I discovered it was from the javascript of another ad partner. Their javascript was throwing an exception and it just happened that prebid.js was catching it.

The original issue I posted here still remains. My next step is to add a stack trace to the logging to see if that unearths anything.

**Comment by eyedar** [comment] 2016-05-03 20:25
@mkendall07 is there a reason why the slots are defined _after_ all of the prebid code? In other words, looking at the page you referred me to (https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_example_gpt.html), the slots are defined on lines 360 and 361. Can they be defined about the prebid code without harm?

I believe you are correct -- there is a timing issue on the page of certain users (remember, this is happening thousands of times per day relative to millions of ad requests, so it's not that prevalent). I think what's happening is that the bids are coming back so fast `pbjs.setTargetingForGPTAsync();` is being executed _before_ the `defineSlot()` calls have even been added to `googletag` queue.

So if that's the case, then moving the `defineSlot()` calls up the page will guarantee that those calls are at the head of the queue.

**Comment by mkendall07** [comment] 2016-05-04 12:59
@eyedar 
I think the reason the example defines the slots later in the page is because that's typically how publishers have already defined googletag on their page and we wanted to be as unobtrusive on the page as possible. With that said, if it does resolve the problem with moving the define slots up in the page, then we should adjust that. Please let me know if it resolves the problem for you.

**Comment by eyedar** [comment] 2016-05-04 17:14
@mkendall07 
I moved the calls up the page as I described above (at the equivalent of line 14 in https://github.com/prebid/Prebid.js/blob/master/integrationExamples/gpt/pbjs_example_gpt.html). Unfortunately, it didn't work -- the errors continued at the same rate.

After that I changed some of the error logging based on what I read in the GPT API docs. There are two flags in `googletag` that identify whether or not the API is "ready" (i.e. fully loaded): `googletag.apiReady` and `googletag.pubadsReady`. I changed the logging code to the following:

```
if (!utils.isFn(window.googletag.pubads().getSlots)) {
    if (window.googletag.apiReady) {
      // GPT API is fully loaded
      if (window.googletag.pubadsReady) {
        // Pubads service is fully loaded
        utils.logError('window.googletag.pubads().getSlots is not a function even though GPT API and Pubads service are fully loaded');
      } else {
        utils.logError('window.googletag.pubads().getSlots is not a function even though GPT API is loaded because the Pubads service is not loaded');
      }    
    } else {
      utils.logError('window.googletag.pubads().getSlots is not a function because GPT API is not loaded');
    }    
    return;
  }
```

I let this run for several hours and then tabulated the results. When there was an error (i.e. `getSlots()` was not a function):
- 95.7% of the time the error message was `window.googletag.pubads().getSlots is not a function even though GPT API and Pubads service are fully loaded`
- 4.3% of the time the error message was `window.googletag.pubads().getSlots is not a function because GPT API is not loaded`
- there were actually zero instances of the message `window.googletag.pubads().getSlots is not a function even though GPT API is loaded because the Pubads service is not loaded`

So what this says to me is that we're likely dealing with two different issues. I am going to worry about the most prevalent one first. At this point my current theory for why `getSlots()` is not a function even though GPT and Pubads are ready is that for some reason `defineSlot()` failed. I don't really know why it would fail if GPT is loaded but I will add some logging to see if there is ever a case where `defineSlot()` returns a null value instead of a Slot.

The only other theory I have at this point is that maybe some users are getting some version of the GPT API that really doesn't have `getSlots()` defined. Again, **I don't see `getSlots()` in the GPT API documentation**. Does that mean Google has deprecated it? Are the phasing it out? Are they just hiding it for some reason? 

I will continue to keep you posted.

**Comment by eyedar** [comment] 2016-05-04 17:46
I've already debunked my `defineSlot()` fail theory. I added logging code to check to see if one of my slots is null, and 100% of the time it is not null.

So let me review where we're at:
- for some small percentage of users, we're finding `googletag.pubads().getSlots()` is not a function
- in 95.7% of those cases, the GPT library and Pubads service are fully loaded and the slots have all been defined already with `defineSlot()`

I left with my theory that `getSlots()` really isn't defined in the GPT library for these users. This wouldn't surprise me given that it's not in the documentation. 

Any advice here would be greatly appreciated. I'm at a bit of a dead end. I would definitely like some insights as to why/how `getSlots()` is used given that it's not in the documentation.

Thanks.

**Comment by mkendall07** [comment] 2016-05-05 21:09
@eyedar 
We just inspected the `googletag.pubads()` object and found the method available, even though it's not documented. 

You seem to be doing everything right. Can you post your code for review?

**Comment by mkendall07** [comment] 2016-05-05 21:34
@eyedar 
Also - it's worth mentioning that you can actually set the targeting yourself if you keep a reference to all the `slot` objects and get the targeting keys from prebid using `pbjs.getAdserverTargeting`. Of course this doesn't explain the root cause of the issue but it does offer a workaround.

**Comment by eyedar** [comment] 2016-05-10 00:17
@mkendall07 I just put a snapshot of our code here: https://github.com/eyedar/Prebid.js/blob/eyedar-debug/integrationExamples/gpt/gpt_bidder.html

This doesn't actually work as a standalone page, but it shows our setup in a standalone file.

You inspect `googletag.pubads()` and of course the method is there. And I inspect it and it's there. But neither one of us are an example of a client where we're getting the error that `getSlots()` isn't defined. I'm not convinced that we're all getting the same GPT library. Yes, we might all be loading the GPT library from the same URL, but what Google ultimately loads might be different based on some attributes of the particular client. This might explain why Google is not documenting `getSlots()`. But not putting it in the documentation, they are not guaranteeing that it will be available.

Of course this is all supposition on my part at this point but it's all I have to go on. I added user agent to my logging and didn't see any trend.

My next idea is to actually talk to Google about this. As a publisher, I can ask them and they will answer me. I suppose for non-publishers they might not be as open.

**Comment by eyedar** [comment] 2016-05-11 03:55
@mkendall07 I got a response from Google. They indeed said that function used to be in the GPT docs but it is no longer supported. Even though it's still in the library for us, there are no guarantees on consistency of usage or availability. They also mentioned that others have asked that this officially be put back in the library as it was before, but there are no promises or firm plans to do so.

They told me the solution is to keep track of the slots on the page ourselves. Just as you suggested, I will set the targeting myself because I'm already keeping a reference to my `slot` objects. I'm not sure what it mean for you and the public library other than asking all publishers to do the same.

**Comment by mkendall07** [comment] 2016-05-11 13:33
@eyedar 
Thank you very much for following up with the response. We will have to consider a new strategy for this potentially if they are removing support for it...

**Comment by protonate** [comment] 2016-06-07 20:58
Closing, please reopen if new info.

**Closed by protonate** 2016-06-07 20:58 UTC
Labels: feature

**Comment by sameerr25** [comment] 2017-08-01 12:31
I think getSlots call can be called within: 
```
window.googletag.cmd.push(function(){
console.log(window.googletag.pubads().getSlots());
});
```
Works for me each time and reference is right here: https://developers.google.com/doubleclick-gpt/reference#googletagservice

**Comment by matsaman** [comment] 2019-05-29 17:00
@sameerr25
You're probably using an old or customized `gpt.js`.

**Comment by benjaminclot** [comment] 2019-05-30 13:33
@matsaman why would you say that? `getSlots()` is an official method of the GPT Reference:
https://developers.google.com/doubleclick-gpt/reference#googletag.Service_getSlots

**Comment by matsaman** [comment] 2020-03-04 18:25
@benjaminclot Because getSlots also broke for an implementation I have to deal with, and the only apparent change was the specific version of gpt.js used. Switched back to the old version, and it worked; switched to the new, and it didn't. If you think Google does proper QA, you are in for disappointment.

**Comment by matsaman** [comment] 2020-03-04 18:50
@benjaminclot Actually I think one other aspect that changed was that we went from a same-origin copy of gpt.js to Google's regular remote (for us) copy. So that would be something worth debugging also.

**Comment by matsaman** [comment] 2020-03-04 19:07
@benjaminclot Double-checked and the same-origin vs cross-origin isn't an issue, it's whatever has changed in the script itself alone.
