### ISSUE TITLE
Click Measurement

### ISSUE THREAD

**Issue by sasanfarokh** [prebid/Prebid.js#7600] opened 2021-10-19 14:36 UTC
## Type of issue
Feature Request

## Description
Could we measure clicks inside Prebid.js adapters? 
Ads are served inside iframes, so clicks inside iframes could not be detected.
I was thinking if Prebid.js supports click measurement or how else could we detect clicks inside iframe ads?

Thanks a lot.

**Comment by patmmccann** [comment] 2021-10-20 21:11
dupe of #6130

**Closed as completed by patmmccann** 2021-10-20 21:11 UTC
