### ISSUE TITLE
Add TTL Validation for Suppressing Expired Ads

### ISSUE THREAD

**Issue by pm-azhar-mulla** [prebid/Prebid.js#12521] opened 2024-11-29 05:59 UTC
## Type of issue

Feature
## Description

Currently, the ttl (Time-to-Live) property is not utilized when rendering an ad. This results in ads being displayed even after they are technically expired. By leveraging the ttl property, we can determine whether an ad has expired and suppress its rendering if needed.

## Proposed Enhancement:
Introduce functionality to validate the ttl property before rendering an ad. If the ad has exceeded its ttl value and the suppressStaleRender property is enabled, the system should suppress the rendering of the expired ad. This would function similarly to the [adId validation mechanism](https://github.com/prebid/Prebid.js/blob/9.21.0/src/adRendering.js#L181).

Publishers can enable the `suppressStaleRender` property to prevent expired ads from being displayed, ensuring a better user experience and avoiding potential compliance or quality issues.

**Comment by patmmccann** [comment] 2024-12-01 02:18
Stale render has a different meaning; I believe it suppresses ads from rendering twice

**Comment by patmmccann** [comment] 2024-12-02 16:13
yes, i would suggest a new flag. I think stale bids are poorly named, as one would naturally think they are bids past their shelf life, but for whatever reason they indeed have a different definition here. Perhaps we could improve the verbiage in the messages.

**Comment by patmmccann** [comment] 2024-12-02 16:14
@pm-azhar-mulla is this a dupe of https://github.com/prebid/Prebid.js/issues/11270 ?

**Closed** 2024-12-04 14:27 UTC
