### ISSUE TITLE
'ix' unsupported bidder in prebid server.

### ISSUE THREAD

**Issue by RajasekarPR** [prebid/Prebid.js#3044] opened 2018-09-04 05:33 UTC
Appnexus prebid server returns 'ix' as unsupported bidder.

Getting the below error when using below auction endpoint 

400. Bad request

Error Message : Invalid request: request.imp[0].ext contains unknown bidder: ix. Did you forget an alias in request.ext.prebid.aliases?

Endpoint : https://prebid.adnxs.com/pbs/v1/openrtb2/auction

Kindly do the needful.

**Comment by RajasekarPR** [comment] 2018-09-05 09:11
Any update on this ?

**Comment by akira28** [comment] 2018-09-05 09:19
Same here. This is preventing us implementing s2s on our website. This PR should solve the issue, but it was not merged for some reason: https://github.com/prebid/Prebid.js/pull/2916

**Comment by RajasekarPR** [comment] 2018-09-05 10:13
By adding the below code in modules/prebidServerBidAdapter/index.js . I can able to resolve this issue.

if (bid.bidder === 'ix') {
aliases.ix = 'indexExchange';
}

Add the above the code after line number 412.

**Comment by bretg** [comment] 2018-09-05 16:53
https://github.com/prebid/prebid-server/issues/657 tracks a resolution on the Prebid Server side.

**Comment by mkendall07** [comment] 2018-09-19 20:47
I pinged index on this - they are going to fix.

**Comment by mkendall07** [comment] 2018-09-19 21:04
closing as duplicate of https://github.com/prebid/Prebid.js/issues/2851

**Closed by mkendall07** 2018-09-19 21:04 UTC
Labels: bug

**Comment by vi-oder-was** [comment] 2018-10-02 11:51
@mkendall07 We're currently facing the same issue and need a solution for this. Please can you clearify what's the solution on this?
