### ISSUE TITLE
Calling  pbjs.que.push multiple times give error

### ISSUE THREAD

**Issue by dperfetto** [prebid/Prebid.js#1347] opened 2017-07-06 08:27 UTC
## Type of issue

BUG
## Description
I'm trying to implement the lazy loading of the ads. Calling pbjs.que.push multiple times gives 
`TypeError: e.bids.map is not a function`
Seems like that while an auction is in progress is not possible to push any other requests into the prebid queue.

As a workaround I created a queue where i push the requests and elaborate one at time after the  bidsBackHandler callback is invoked.

Am I doing something wrong? Anyone experienced the same problem?

**Comment by dbemiller** [comment] 2017-07-06 14:35
I believe that `pbjs.que.push` should work whenever. Its only purpose is so that you can queue up prebid work while the script loads async... so your functions get executed either immediately, or once the prebid script loads.

You can see the code which processes the queue and monkey-patches the `que.push` function here: https://github.com/prebid/Prebid.js/blob/master/src/prebid.js#L753

I would suspect your error caused by the content of the function that you're pushing--not the push itself. Without more information on what's being done, though, it's hard to tell.

**Comment by dbemiller** [comment] 2017-08-02 14:02
Closing because we can't troubleshoot without more details.

@dperfetto feel free to open a new bug if you still think you're having issues.

**Closed by dbemiller** 2017-08-02 14:02 UTC
